@startuml
'skinparam handwritten true
'skinparam defaultFontName Segoe Print
scale max 845 height

skinparam node {
  borderColor grey
}
skinparam component {
  borderColor<<active>> green
  borderColor<<passive>> grey
}
skinparam node {
  backgroundColor<<hertz>> antiquewhite
  borderColor<<ebx>> navy
}

package "Application Tier" {
  node "ebxappprod01" <<EBX>> {
    [Primary EBX Server] <<Active>> as ebx1
  }
  node "ebxappprod02" <<EBX>> {
    [Standby EBX Server] <<Passive>> as ebx2
    [Health Monitor] <<Script>> as monitor
  }
  node "ebxappprodilb" <<Hertz>> {
    [Azure Load Balancer] as ebxproxy
  }
  [ebxproxy] -[bold,#green]- ebx1
  [ebxproxy] .[#red]. ebx2
  [monitor] -d- ebx1
  [monitor] -d- ebx2
  [monitor] -u- [ebxproxy]
}

@enduml
