package com.hertz.mdm.common.path;

import com.orchestranetworks.schema.Path;
/**
 * Generated by EBX5 5.7.1 fix B [1034:0005], at  2017/10/30 13:11:37 [EDT].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: hertz-mdm, path: /WEB-INF/ebx/schemas/CommonReferenceDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface CommonReferencePaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Prefix:  ''.
	// Statistics:
	//		555 path constants.
	//		235 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Acriss {
		private static final Path _Root_Acriss = _Root.add("acriss");
		public static Path getPathInSchema()
		{
			return _Root_Acriss;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_AddressType {
		private static final Path _Root_AddressType = _Root.add("AddressType");
		public static Path getPathInSchema()
		{
			return _Root_AddressType;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Airline {
		private static final Path _Root_Airline = _Root.add("Airline");
		public static Path getPathInSchema()
		{
			return _Root_Airline;
		}
	public static final Path _IATA = Path.parse("./IATA");
	public static final Path _Name = Path.parse("./name");
	public static final Path _Alias = Path.parse("./Alias");
	public static final Path _CallSign = Path.parse("./callSign");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Airport {
		private static final Path _Root_Airport = _Root.add("Airport");
		public static Path getPathInSchema()
		{
			return _Root_Airport;
		}
	public static final Path _IataFAA = Path.parse("./iataFAA");
	public static final Path _IataFcc = Path.parse("./iataFcc");
	public static final Path _Name = Path.parse("./Name");
	public static final Path _City = Path.parse("./City");
	public static final Path _Country = Path.parse("./Country");
	public static final Path _Region = Path.parse("./region");
	public static final Path _Latitude = Path.parse("./Latitude");
	public static final Path _Longitude = Path.parse("./Longitude");
	public static final Path _Altitude = Path.parse("./Altitude");
	public static final Path _Timezone = Path.parse("./Timezone");
	public static final Path _DST = Path.parse("./DST");
	public static final Path _IsAirportOperations = Path.parse("./isAirportOperations");
	public static final Path _IsMilitary = Path.parse("./isMilitary");
	public static final Path _Municipality = Path.parse("./municipality");
	public static final Path _AirportType = Path.parse("./airportType");
	public static final Path _Identifier = Path.parse("./identifier");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_City {
		private static final Path _Root_City = _Root.add("City");
		public static Path getPathInSchema()
		{
			return _Root_City;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _Country = Path.parse("./country");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Continent {
		private static final Path _Root_Continent = _Root.add("Continent");
		public static Path getPathInSchema()
		{
			return _Root_Continent;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Country_ISO31661 {
		private static final Path _Root_Country_ISO31661 = _Root.add("Country_ISO3166-1");
		public static Path getPathInSchema()
		{
			return _Root_Country_ISO31661;
		}
	public static final Path _ISO31661_integer = Path.parse("./ISO3166-1_integer");
	public static final Path _ISO31661_alpha2 = Path.parse("./ISO3166-1_alpha-2");
	public static final Path _ISO31661_alpha3 = Path.parse("./ISO3166-1_alpha-3");
	public static final Path _ISO31661_numeric = Path.parse("./ISO3166-1_numeric");
	public static final Path _ShortName = Path.parse("./shortName");
	public static final Path _ShortName_fr = Path.parse("./shortName_fr");
	public static final Path _Itu = Path.parse("./itu");
	public static final Path _Marc = Path.parse("./marc");
	public static final Path _Wmo = Path.parse("./wmo");
	public static final Path _Ds = Path.parse("./ds");
	public static final Path _Dial = Path.parse("./dial");
	public static final Path _Fifa = Path.parse("./fifa");
	public static final Path _Fips = Path.parse("./fips");
	public static final Path _Gaul = Path.parse("./gaul");
	public static final Path _Ioc = Path.parse("./ioc");
	public static final Path _CurrencyAlphaCode = Path.parse("./currency-alpha-code");
	public static final Path _CurrencyCountryName = Path.parse("./currency-country-name");
	public static final Path _CurrencyMinorUnit = Path.parse("./currency-minor-unit");
	public static final Path _CurrencyName = Path.parse("./currency-name");
	public static final Path _CurrencyNumericCode = Path.parse("./currency-numeric-code");
	public static final Path _IsIdependent = Path.parse("./is-idependent");
	public static final Path _Subdivisions = Path.parse("./subdivisions");
	public static final Path _Timezones = Path.parse("./timezones");
	public static final Path _Cities = Path.parse("./cities");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_CountryTimeZoneRelationship {
		private static final Path _Root_CountryTimeZoneRelationship = _Root.add("CountryTimeZoneRelationship");
		public static Path getPathInSchema()
		{
			return _Root_CountryTimeZoneRelationship;
		}
	public static final Path _Country = Path.parse("./country");
	public static final Path _Timezone = Path.parse("./timezone");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Currency {
		private static final Path _Root_Currency = _Root.add("Currency");
		public static Path getPathInSchema()
		{
			return _Root_Currency;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_DaysOfWeek {
		private static final Path _Root_DaysOfWeek = _Root.add("DaysOfWeek");
		public static Path getPathInSchema()
		{
			return _Root_DaysOfWeek;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _DayOfTheWeek = Path.parse("./dayOfTheWeek");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_EMailAddressType {
		private static final Path _Root_EMailAddressType = _Root.add("EMailAddressType");
		public static Path getPathInSchema()
		{
			return _Root_EMailAddressType;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_EmailNotification {
		private static final Path _Root_EmailNotification = _Root.add("emailNotification");
		public static Path getPathInSchema()
		{
			return _Root_EmailNotification;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _Domain = Path.parse("./domain");
	public static final Path _ProjectType = Path.parse("./projectType");
	public static final Path __projectTypeName = Path.parse("./_projectTypeName");
	public static final Path _ProjectTypeEvent = Path.parse("./projectTypeEvent");
	public static final Path _Message = Path.parse("./message");
	public static final Path _BusnessParties = Path.parse("./busnessParties");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_EMailNotificationBusinessPartyRelationship {
		private static final Path _Root_EMailNotificationBusinessPartyRelationship = _Root.add("EMailNotificationBusinessPartyRelationship");
		public static Path getPathInSchema()
		{
			return _Root_EMailNotificationBusinessPartyRelationship;
		}
	public static final Path _EmailNotification = Path.parse("./emailNotification");
	public static final Path _BusinessParty = Path.parse("./businessParty");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_GeographicArea {
		private static final Path _Root_GeographicArea = _Root.add("GeographicArea");
		public static Path getPathInSchema()
		{
			return _Root_GeographicArea;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Language {
		private static final Path _Root_Language = _Root.add("language");
		public static Path getPathInSchema()
		{
			return _Root_Language;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_MeasurementType {
		private static final Path _Root_MeasurementType = _Root.add("MeasurementType");
		public static Path getPathInSchema()
		{
			return _Root_MeasurementType;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Note {
		private static final Path _Root_Note = _Root.add("Note");
		public static Path getPathInSchema()
		{
			return _Root_Note;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _NoteType = Path.parse("./noteType");
	public static final Path _Domain = Path.parse("./domain");
	public static final Path _CreatedBy = Path.parse("./createdBy");
	public static final Path _CreatedDate = Path.parse("./createdDate");
	public static final Path _Note = Path.parse("./note");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_NoteType {
		private static final Path _Root_NoteType = _Root.add("NoteType");
		public static Path getPathInSchema()
		{
			return _Root_NoteType;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_OfficialAirlineGuide {
		private static final Path _Root_OfficialAirlineGuide = _Root.add("OfficialAirlineGuide");
		public static Path getPathInSchema()
		{
			return _Root_OfficialAirlineGuide;
		}
	public static final Path _ExtendedOAGCode = Path.parse("./extendedOAGCode");
	public static final Path _IataCode = Path.parse("./iataCode");
	public static final Path __airport = Path.parse("./_airport");
	public static final Path _OagVicinity = Path.parse("./oagVicinity");
	public static final Path _LocationNumber = Path.parse("./locationNumber");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_PaymentType {
		private static final Path _Root_PaymentType = _Root.add("PaymentType");
		public static Path getPathInSchema()
		{
			return _Root_PaymentType;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_PhoneType {
		private static final Path _Root_PhoneType = _Root.add("PhoneType");
		public static Path getPathInSchema()
		{
			return _Root_PhoneType;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_ProjectUserTaskLog {
		private static final Path _Root_ProjectUserTaskLog = _Root.add("ProjectUserTaskLog");
		public static Path getPathInSchema()
		{
			return _Root_ProjectUserTaskLog;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _ProjectName = Path.parse("./projectName");
	public static final Path _ProjectType = Path.parse("./projectType");
	public static final Path _UserTaskName = Path.parse("./userTaskName");
	public static final Path _OfferedToRole = Path.parse("./offeredToRole");
	public static final Path _AllocatedUser = Path.parse("./allocatedUser");
	public static final Path _TaskStartEndTimestamp = Path.parse("./taskStartEndTimestamp");
	public static final Path _TaskStartEndTimestamp_StartDateTime = Path.parse("./taskStartEndTimestamp/startDateTime");
	public static final Path _TaskStartEndTimestamp_EndDateTime = Path.parse("./taskStartEndTimestamp/endDateTime");
	public static final Path _IsUserTaskOverdue = Path.parse("./isUserTaskOverdue");
	public static final Path _IsUserTaskActive = Path.parse("./isUserTaskActive");
	} 

	// Table type path
	public final class _Root_RentalCarBrand {
		private static final Path _Root_RentalCarBrand = _Root.add("RentalCarBrand");
		public static Path getPathInSchema()
		{
			return _Root_RentalCarBrand;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _IsHertzBrand = Path.parse("./isHertzBrand");
	public static final Path _RentalCarBrandCode = Path.parse("./rentalCarBrandCode");
	public static final Path _IntelligentLocationIdBrandCode = Path.parse("./intelligentLocationIdBrandCode");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_SourceSystem {
		private static final Path _Root_SourceSystem = _Root.add("SourceSystem");
		public static Path getPathInSchema()
		{
			return _Root_SourceSystem;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_StateProvinceTimeZoneRelationship {
		private static final Path _Root_StateProvinceTimeZoneRelationship = _Root.add("StateProvinceTimeZoneRelationship");
		public static Path getPathInSchema()
		{
			return _Root_StateProvinceTimeZoneRelationship;
		}
	public static final Path _StateProvince = Path.parse("./stateProvince");
	public static final Path _Timezone = Path.parse("./timezone");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Subdivision_ISO31662 {
		private static final Path _Root_Subdivision_ISO31662 = _Root.add("Subdivision_ISO3166-2");
		public static Path getPathInSchema()
		{
			return _Root_Subdivision_ISO31662;
		}
	public static final Path _ISO31662_Subdivision = Path.parse("./ISO3166-2_Subdivision");
	public static final Path _ISO31662_SubdivisionName = Path.parse("./ISO3166-2_SubdivisionName");
	public static final Path _ISO31662_SubdivisionAlternateNames = Path.parse("./ISO3166-2_SubdivisionAlternateNames");
	public static final Path _ISO31661_Integer = Path.parse("./ISO3166-1_Integer");
	public static final Path _Timezones = Path.parse("./timezones");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_TimeZone {
		private static final Path _Root_TimeZone = _Root.add("TimeZone");
		public static Path getPathInSchema()
		{
			return _Root_TimeZone;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_UnitOfMeasure {
		private static final Path _Root_UnitOfMeasure = _Root.add("UnitOfMeasure");
		public static Path getPathInSchema()
		{
			return _Root_UnitOfMeasure;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _MeasurementSystem = Path.parse("./measurementSystem");
	public static final Path _UomGroup = Path.parse("./uomGroup");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Website {
		private static final Path _Root_Website = _Root.add("Website");
		public static Path getPathInSchema()
		{
			return _Root_Website;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_MDMCommonReferenceTable {
		private static final Path _Root_MDMCommonReferenceTable = _Root.add("MDMCommonReferenceTable");
		public static Path getPathInSchema()
		{
			return _Root_MDMCommonReferenceTable;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _MdmReplicationTable = Path.parse("./mdmReplicationTable");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	// ===============================================

}
