package com.hertz.mdm.vehicle.path;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX5 5.8.1 [1067], at  2017/12/21 09:45:40 [CST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: hertz-mdm, path: /WEB-INF/ebx/schemas/VehicleReferenceDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface VehicleReferencePaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Statistics:
	//		846 path constants.
	//		329 leaf nodes.
	public static final Path _Root = Path.parse("/root");
	public static final Path _Root_ChromeNewVehicleData = _Root.add("ChromeNewVehicleData");

	// Table type path
	public final class _Root_ChromeNewVehicleData_BodyStyles
	{
		private static final Path _Root_ChromeNewVehicleData_BodyStyles = _Root_ChromeNewVehicleData.add("BodyStyles");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_BodyStyles;
		}
		public static final Path _Root_ChromeNewVehicleData_BodyStyles_StyleID = Path.parse("./styleID");
		public static final Path _Root_ChromeNewVehicleData_BodyStyles_BodyStyle = Path.parse("./bodyStyle");
		public static final Path _Root_ChromeNewVehicleData_BodyStyles_StyleName = Path.parse("./styleName");
		public static final Path _Root_ChromeNewVehicleData_BodyStyles_IsPrimary = Path.parse("./isPrimary");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Categories
	{
		private static final Path _Root_ChromeNewVehicleData_Categories = _Root_ChromeNewVehicleData.add("Categories");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Categories;
		}
		public static final Path _Root_ChromeNewVehicleData_Categories_CategoryID = Path.parse("./categoryID");
		public static final Path _Root_ChromeNewVehicleData_Categories_Category = Path.parse("./category");
		public static final Path _Root_ChromeNewVehicleData_Categories_CategoryTypeFilter = Path.parse("./categoryTypeFilter");
		public static final Path _Root_ChromeNewVehicleData_Categories_CategoryHeaderID = Path.parse("./categoryHeaderID");
		public static final Path _Root_ChromeNewVehicleData_Categories_UserFriendlyName = Path.parse("./userFriendlyName");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_CategoryHeaders
	{
		private static final Path _Root_ChromeNewVehicleData_CategoryHeaders = _Root_ChromeNewVehicleData.add("CategoryHeaders");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_CategoryHeaders;
		}
		public static final Path _Root_ChromeNewVehicleData_CategoryHeaders_CategoryHeaderID = Path.parse("./categoryHeaderID");
		public static final Path _Root_ChromeNewVehicleData_CategoryHeaders_CategoryHeader = Path.parse("./categoryHeader");
		public static final Path _Root_ChromeNewVehicleData_CategoryHeaders_Sequence = Path.parse("./Sequence");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Colors
	{
		private static final Path _Root_ChromeNewVehicleData_Colors = _Root_ChromeNewVehicleData.add("Colors");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Colors;
		}
		public static final Path _Root_ChromeNewVehicleData_Colors_StyleID = Path.parse("./styleID");
		public static final Path _Root_ChromeNewVehicleData_Colors_StyleName = Path.parse("./styleName");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext1Code = Path.parse("./ext1Code");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext2Code = Path.parse("./ext2Code");
		public static final Path _Root_ChromeNewVehicleData_Colors_IntCode = Path.parse("./intCode");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext1ManCode = Path.parse("./ext1ManCode");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext2ManCode = Path.parse("./ext2ManCode");
		public static final Path _Root_ChromeNewVehicleData_Colors_IntManCode = Path.parse("./intManCode");
		public static final Path _Root_ChromeNewVehicleData_Colors_OrderCode = Path.parse("./orderCode");
		public static final Path _Root_ChromeNewVehicleData_Colors_AsTwoTone = Path.parse("./asTwoTone");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext1Desc = Path.parse("./ext1Desc");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext2Desc = Path.parse("./ext2Desc");
		public static final Path _Root_ChromeNewVehicleData_Colors_IntDesc = Path.parse("./intDesc");
		public static final Path _Root_ChromeNewVehicleData_Colors_Condition = Path.parse("./condition");
		public static final Path _Root_ChromeNewVehicleData_Colors_GenericExtColor = Path.parse("./genericExtColor");
		public static final Path _Root_ChromeNewVehicleData_Colors_GenericExt2Color = Path.parse("./genericExt2Color");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext1RGBHex = Path.parse("./ext1RGBHex");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext2RGBHex = Path.parse("./ext2RGBHex");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext1MfrFullCode = Path.parse("./ext1MfrFullCode");
		public static final Path _Root_ChromeNewVehicleData_Colors_Ext2MfrFullCode = Path.parse("./ext2MfrFullCode");
		public static final Path _Root_ChromeNewVehicleData_Colors__exteriorColor = Path.parse("./_exteriorColor");
		public static final Path _Root_ChromeNewVehicleData_Colors__interiorColor = Path.parse("./_interiorColor");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Divisions
	{
		private static final Path _Root_ChromeNewVehicleData_Divisions = _Root_ChromeNewVehicleData.add("Divisions");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Divisions;
		}
		public static final Path _Root_ChromeNewVehicleData_Divisions_DivisionID = Path.parse("./divisionID");
		public static final Path _Root_ChromeNewVehicleData_Divisions_ManufacturerID = Path.parse("./manufacturerID");
		public static final Path _Root_ChromeNewVehicleData_Divisions_DivisionName = Path.parse("./divisionName");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Manufacturers
	{
		private static final Path _Root_ChromeNewVehicleData_Manufacturers = _Root_ChromeNewVehicleData.add("Manufacturers");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Manufacturers;
		}
		public static final Path _Root_ChromeNewVehicleData_Manufacturers_ManufacturerID = Path.parse("./manufacturerID");
		public static final Path _Root_ChromeNewVehicleData_Manufacturers_ManufacturerName = Path.parse("./manufacturerName");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_MktClass
	{
		private static final Path _Root_ChromeNewVehicleData_MktClass = _Root_ChromeNewVehicleData.add("MktClass");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_MktClass;
		}
		public static final Path _Root_ChromeNewVehicleData_MktClass_MktClassID = Path.parse("./mktClassID");
		public static final Path _Root_ChromeNewVehicleData_MktClass_MarketClass = Path.parse("./marketClass");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Models
	{
		private static final Path _Root_ChromeNewVehicleData_Models = _Root_ChromeNewVehicleData.add("Models");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Models;
		}
		public static final Path _Root_ChromeNewVehicleData_Models_ModelID = Path.parse("./modelID");
		public static final Path _Root_ChromeNewVehicleData_Models_HistModelID = Path.parse("./HistModelID");
		public static final Path _Root_ChromeNewVehicleData_Models_ModelYear = Path.parse("./modelYear");
		public static final Path _Root_ChromeNewVehicleData_Models_DivisionID = Path.parse("./divisionID");
		public static final Path _Root_ChromeNewVehicleData_Models_SubdivisionID = Path.parse("./subdivisionID");
		public static final Path _Root_ChromeNewVehicleData_Models_ModelName = Path.parse("./modelName");
		public static final Path _Root_ChromeNewVehicleData_Models_EffectiveDate = Path.parse("./effectiveDate");
		public static final Path _Root_ChromeNewVehicleData_Models_ModelComment = Path.parse("./modelComment");
		public static final Path _Root_ChromeNewVehicleData_Models_Availability = Path.parse("./availability");
		public static final Path _Root_ChromeNewVehicleData_Models__subdivisionName = Path.parse("./_subdivisionName");
		public static final Path _Root_ChromeNewVehicleData_Models__makeModel = Path.parse("./_makeModel");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_OptHeaders
	{
		private static final Path _Root_ChromeNewVehicleData_OptHeaders = _Root_ChromeNewVehicleData.add("OptHeaders");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_OptHeaders;
		}
		public static final Path _Root_ChromeNewVehicleData_OptHeaders_HeaderID = Path.parse("./headerID");
		public static final Path _Root_ChromeNewVehicleData_OptHeaders_Header = Path.parse("./header");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Options
	{
		private static final Path _Root_ChromeNewVehicleData_Options = _Root_ChromeNewVehicleData.add("Options");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Options;
		}
		public static final Path _Root_ChromeNewVehicleData_Options_StyleID = Path.parse("./styleID");
		public static final Path _Root_ChromeNewVehicleData_Options_StyleName = Path.parse("./styleName");
		public static final Path _Root_ChromeNewVehicleData_Options_HeaderID = Path.parse("./headerID");
		public static final Path _Root_ChromeNewVehicleData_Options_Sequence = Path.parse("./sequence");
		public static final Path _Root_ChromeNewVehicleData_Options_OptionCode = Path.parse("./optionCode");
		public static final Path _Root_ChromeNewVehicleData_Options_OptionDescription = Path.parse("./optionDescription");
		public static final Path _Root_ChromeNewVehicleData_Options_OptionKindID = Path.parse("./optionKindID");
		public static final Path _Root_ChromeNewVehicleData_Options_CategoryList = Path.parse("./categoryList");
		public static final Path _Root_ChromeNewVehicleData_Options_Availability = Path.parse("./availability");
		public static final Path _Root_ChromeNewVehicleData_Options_Pon = Path.parse("./pon");
		public static final Path _Root_ChromeNewVehicleData_Options_ExtDescription = Path.parse("./extDescription");
		public static final Path _Root_ChromeNewVehicleData_Options_SupportedLogic = Path.parse("./supportedLogic");
		public static final Path _Root_ChromeNewVehicleData_Options_Unsupported = Path.parse("./unsupported");
		public static final Path _Root_ChromeNewVehicleData_Options_Logic = Path.parse("./logic");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_OptKinds
	{
		private static final Path _Root_ChromeNewVehicleData_OptKinds = _Root_ChromeNewVehicleData.add("OptKinds");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_OptKinds;
		}
		public static final Path _Root_ChromeNewVehicleData_OptKinds_OptionKindID = Path.parse("./optionKindID");
		public static final Path _Root_ChromeNewVehicleData_OptKinds_OptionKind = Path.parse("./optionKind");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Prices
	{
		private static final Path _Root_ChromeNewVehicleData_Prices = _Root_ChromeNewVehicleData.add("Prices");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Prices;
		}
		public static final Path _Root_ChromeNewVehicleData_Prices_StyleID = Path.parse("./styleID");
		public static final Path _Root_ChromeNewVehicleData_Prices_StyleName = Path.parse("./styleName");
		public static final Path _Root_ChromeNewVehicleData_Prices_Sequence = Path.parse("./sequence");
		public static final Path _Root_ChromeNewVehicleData_Prices_OptionCode = Path.parse("./optionCode");
		public static final Path _Root_ChromeNewVehicleData_Prices_PriceRuleDescrption = Path.parse("./priceRuleDescrption");
		public static final Path _Root_ChromeNewVehicleData_Prices_Condition = Path.parse("./condition");
		public static final Path _Root_ChromeNewVehicleData_Prices_Invoice = Path.parse("./invoice");
		public static final Path _Root_ChromeNewVehicleData_Prices_Msrp = Path.parse("./msrp");
		public static final Path _Root_ChromeNewVehicleData_Prices_PriceState = Path.parse("./priceState");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Standards
	{
		private static final Path _Root_ChromeNewVehicleData_Standards = _Root_ChromeNewVehicleData.add("Standards");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Standards;
		}
		public static final Path _Root_ChromeNewVehicleData_Standards_StyleID = Path.parse("./styleID");
		public static final Path _Root_ChromeNewVehicleData_Standards_HeaderID = Path.parse("./headerID");
		public static final Path _Root_ChromeNewVehicleData_Standards_Sequence = Path.parse("./sequence");
		public static final Path _Root_ChromeNewVehicleData_Standards_StyleName = Path.parse("./styleName");
		public static final Path _Root_ChromeNewVehicleData_Standards_Standard = Path.parse("./standard");
		public static final Path _Root_ChromeNewVehicleData_Standards_CategoryList = Path.parse("./categoryList");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_StdHeaders
	{
		private static final Path _Root_ChromeNewVehicleData_StdHeaders = _Root_ChromeNewVehicleData.add("StdHeaders");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_StdHeaders;
		}
		public static final Path _Root_ChromeNewVehicleData_StdHeaders_HeaderID = Path.parse("./headerID");
		public static final Path _Root_ChromeNewVehicleData_StdHeaders_Header = Path.parse("./header");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_StyleCats
	{
		private static final Path _Root_ChromeNewVehicleData_StyleCats = _Root_ChromeNewVehicleData.add("StyleCats");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_StyleCats;
		}
		public static final Path _Root_ChromeNewVehicleData_StyleCats_StyleID = Path.parse("./styleID");
		public static final Path _Root_ChromeNewVehicleData_StyleCats_CategoryID = Path.parse("./categoryID");
		public static final Path _Root_ChromeNewVehicleData_StyleCats_StyleName = Path.parse("./styleName");
		public static final Path _Root_ChromeNewVehicleData_StyleCats_FeatureType = Path.parse("./featureType");
		public static final Path _Root_ChromeNewVehicleData_StyleCats_Sequence = Path.parse("./sequence");
		public static final Path _Root_ChromeNewVehicleData_StyleCats_State = Path.parse("./state");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Styles
	{
		private static final Path _Root_ChromeNewVehicleData_Styles = _Root_ChromeNewVehicleData.add("Styles");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Styles;
		}
		public static final Path _Root_ChromeNewVehicleData_Styles_StyleID = Path.parse("./styleID");
		public static final Path _Root_ChromeNewVehicleData_Styles_HistStyleID = Path.parse("./histStyleID");
		public static final Path _Root_ChromeNewVehicleData_Styles_ModelID = Path.parse("./modelID");
		public static final Path _Root_ChromeNewVehicleData_Styles_ModelYear = Path.parse("./modelYear");
		public static final Path _Root_ChromeNewVehicleData_Styles_Sequence = Path.parse("./sequence");
		public static final Path _Root_ChromeNewVehicleData_Styles_StyleCode = Path.parse("./styleCode");
		public static final Path _Root_ChromeNewVehicleData_Styles_FullStyleCode = Path.parse("./fullStyleCode");
		public static final Path _Root_ChromeNewVehicleData_Styles_StyleName = Path.parse("./styleName");
		public static final Path _Root_ChromeNewVehicleData_Styles_TrueBasePrice = Path.parse("./trueBasePrice");
		public static final Path _Root_ChromeNewVehicleData_Styles_Invoice = Path.parse("./invoice");
		public static final Path _Root_ChromeNewVehicleData_Styles_Msrp = Path.parse("./msrp");
		public static final Path _Root_ChromeNewVehicleData_Styles_Destination = Path.parse("./destination");
		public static final Path _Root_ChromeNewVehicleData_Styles_StyleCVCList = Path.parse("./styleCVCList");
		public static final Path _Root_ChromeNewVehicleData_Styles_MktClassID = Path.parse("./mktClassID");
		public static final Path _Root_ChromeNewVehicleData_Styles_StyleNameWOTrim = Path.parse("./styleNameWOTrim");
		public static final Path _Root_ChromeNewVehicleData_Styles_Trim = Path.parse("./trim");
		public static final Path _Root_ChromeNewVehicleData_Styles_PassengerCapacity = Path.parse("./passengerCapacity");
		public static final Path _Root_ChromeNewVehicleData_Styles_PassangerDoors = Path.parse("./passangerDoors");
		public static final Path _Root_ChromeNewVehicleData_Styles_ManualTrans = Path.parse("./manualTrans");
		public static final Path _Root_ChromeNewVehicleData_Styles_AutoTrans = Path.parse("./autoTrans");
		public static final Path _Root_ChromeNewVehicleData_Styles_FrontWD = Path.parse("./frontWD");
		public static final Path _Root_ChromeNewVehicleData_Styles_RearWD = Path.parse("./rearWD");
		public static final Path _Root_ChromeNewVehicleData_Styles_AllWD = Path.parse("./allWD");
		public static final Path _Root_ChromeNewVehicleData_Styles_FourWD = Path.parse("./fourWD");
		public static final Path _Root_ChromeNewVehicleData_Styles_StepSide = Path.parse("./stepSide");
		public static final Path _Root_ChromeNewVehicleData_Styles_Caption = Path.parse("./caption");
		public static final Path _Root_ChromeNewVehicleData_Styles_Availability = Path.parse("./availability");
		public static final Path _Root_ChromeNewVehicleData_Styles_PriceState = Path.parse("./priceState");
		public static final Path _Root_ChromeNewVehicleData_Styles_AutoBuilderStyleID = Path.parse("./autoBuilderStyleID");
		public static final Path _Root_ChromeNewVehicleData_Styles_CfModelName = Path.parse("./cfModelName");
		public static final Path _Root_ChromeNewVehicleData_Styles_CfStyleName = Path.parse("./cfStyleName");
		public static final Path _Root_ChromeNewVehicleData_Styles_CfDriveTrain = Path.parse("./cfDriveTrain");
		public static final Path _Root_ChromeNewVehicleData_Styles_CfBodyType = Path.parse("./cfBodyType");
		public static final Path _Root_ChromeNewVehicleData_Styles__makeModel = Path.parse("./_makeModel");
		public static final Path _Root_ChromeNewVehicleData_Styles_BodyStyles = Path.parse("./bodyStyles");
		public static final Path _Root_ChromeNewVehicleData_Styles_Options = Path.parse("./options");
		public static final Path _Root_ChromeNewVehicleData_Styles_Colors = Path.parse("./colors");
		public static final Path _Root_ChromeNewVehicleData_Styles_Prices = Path.parse("./prices");
		public static final Path _Root_ChromeNewVehicleData_Styles_Standards = Path.parse("./standards");
		public static final Path _Root_ChromeNewVehicleData_Styles_StyleCategories = Path.parse("./styleCategories");
		public static final Path _Root_ChromeNewVehicleData_Styles_TechSpecifications = Path.parse("./techSpecifications");
		public static final Path _Root_ChromeNewVehicleData_Styles_Styleimagelinks = Path.parse("./styleimagelinks");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_StyleImageLinks
	{
		private static final Path _Root_ChromeNewVehicleData_StyleImageLinks = _Root_ChromeNewVehicleData.add("StyleImageLinks");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_StyleImageLinks;
		}
		public static final Path _Root_ChromeNewVehicleData_StyleImageLinks_StyleID = Path.parse("./styleID");
		public static final Path _Root_ChromeNewVehicleData_StyleImageLinks_ImageID = Path.parse("./imageID");
		public static final Path _Root_ChromeNewVehicleData_StyleImageLinks_ViewType = Path.parse("./viewType");
		public static final Path _Root_ChromeNewVehicleData_StyleImageLinks_ImageLink = Path.parse("./imageLink");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Subdivisions
	{
		private static final Path _Root_ChromeNewVehicleData_Subdivisions = _Root_ChromeNewVehicleData.add("Subdivisions");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Subdivisions;
		}
		public static final Path _Root_ChromeNewVehicleData_Subdivisions_ModelYear = Path.parse("./modelYear");
		public static final Path _Root_ChromeNewVehicleData_Subdivisions_DivisionID = Path.parse("./divisionID");
		public static final Path _Root_ChromeNewVehicleData_Subdivisions_SubdivisionID = Path.parse("./subdivisionID");
		public static final Path _Root_ChromeNewVehicleData_Subdivisions_HistSubdivisionID = Path.parse("./histSubdivisionID");
		public static final Path _Root_ChromeNewVehicleData_Subdivisions_SubdivisionName = Path.parse("./subdivisionName");
		public static final Path _Root_ChromeNewVehicleData_Subdivisions_Year = Path.parse("./Year");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_TechSpecs
	{
		private static final Path _Root_ChromeNewVehicleData_TechSpecs = _Root_ChromeNewVehicleData.add("TechSpecs");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_TechSpecs;
		}
		public static final Path _Root_ChromeNewVehicleData_TechSpecs_StyleID = Path.parse("./styleID");
		public static final Path _Root_ChromeNewVehicleData_TechSpecs_TitleID = Path.parse("./titleID");
		public static final Path _Root_ChromeNewVehicleData_TechSpecs_Sequence = Path.parse("./sequence");
		public static final Path _Root_ChromeNewVehicleData_TechSpecs_StyleName = Path.parse("./styleName");
		public static final Path _Root_ChromeNewVehicleData_TechSpecs_Text = Path.parse("./text");
		public static final Path _Root_ChromeNewVehicleData_TechSpecs_Condition = Path.parse("./condition");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_TechTitleHeader
	{
		private static final Path _Root_ChromeNewVehicleData_TechTitleHeader = _Root_ChromeNewVehicleData.add("TechTitleHeader");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_TechTitleHeader;
		}
		public static final Path _Root_ChromeNewVehicleData_TechTitleHeader_TechTitleHeaderID = Path.parse("./techTitleHeaderID");
		public static final Path _Root_ChromeNewVehicleData_TechTitleHeader_TechTitleHeaderText = Path.parse("./techTitleHeaderText");
		public static final Path _Root_ChromeNewVehicleData_TechTitleHeader_Sequence = Path.parse("./sequence");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_TechTitles
	{
		private static final Path _Root_ChromeNewVehicleData_TechTitles = _Root_ChromeNewVehicleData.add("TechTitles");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_TechTitles;
		}
		public static final Path _Root_ChromeNewVehicleData_TechTitles_TitleID = Path.parse("./titleID");
		public static final Path _Root_ChromeNewVehicleData_TechTitles_Sequence = Path.parse("./sequence");
		public static final Path _Root_ChromeNewVehicleData_TechTitles_Title = Path.parse("./title");
		public static final Path _Root_ChromeNewVehicleData_TechTitles_TechTitleHeaderID = Path.parse("./TechTitleHeaderID");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Version
	{
		private static final Path _Root_ChromeNewVehicleData_Version = _Root_ChromeNewVehicleData.add("Version");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Version;
		}
		public static final Path _Root_ChromeNewVehicleData_Version_Product = Path.parse("./product");
		public static final Path _Root_ChromeNewVehicleData_Version_DataVersion = Path.parse("./dataVersion");
		public static final Path _Root_ChromeNewVehicleData_Version_DateReleaseID = Path.parse("./dateReleaseID");
		public static final Path _Root_ChromeNewVehicleData_Version_SchemaName = Path.parse("./schemaName");
		public static final Path _Root_ChromeNewVehicleData_Version_SchemaVersion = Path.parse("./schemaVersion");
		public static final Path _Root_ChromeNewVehicleData_Version_Country = Path.parse("./country");
		public static final Path _Root_ChromeNewVehicleData_Version_Language = Path.parse("./language");
	} 

	// Table type path
	public final class _Root_ChromeNewVehicleData_Year
	{
		private static final Path _Root_ChromeNewVehicleData_Year = _Root_ChromeNewVehicleData.add("Year");
		public static Path getPathInSchema()
		{
			return _Root_ChromeNewVehicleData_Year;
		}
		public static final Path _Root_ChromeNewVehicleData_Year_Division = Path.parse("./Division");
		public static final Path _Root_ChromeNewVehicleData_Year_Year = Path.parse("./Year");
	} 

	// Table type path
	public final class _Root_CarClass
	{
		private static final Path _Root_CarClass = _Root.add("CarClass");
		public static Path getPathInSchema()
		{
			return _Root_CarClass;
		}
		public static final Path _Root_CarClass_CarClass = Path.parse("./carClass");
		public static final Path _Root_CarClass_Country = Path.parse("./country");
		public static final Path _Root_CarClass__countryName = Path.parse("./_countryName");
		public static final Path _Root_CarClass_Description = Path.parse("./description");
		public static final Path _Root_CarClass_PaymentTypes = Path.parse("./paymentTypes");
		public static final Path _Root_CarClass_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_CarClass_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_CarClass_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_CarClass_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_CarClassPaymentTypeRelationship
	{
		private static final Path _Root_CarClassPaymentTypeRelationship = _Root.add("CarClassPaymentTypeRelationship");
		public static Path getPathInSchema()
		{
			return _Root_CarClassPaymentTypeRelationship;
		}
		public static final Path _Root_CarClassPaymentTypeRelationship_CarClass = Path.parse("./carClass");
		public static final Path _Root_CarClassPaymentTypeRelationship_PaymentType = Path.parse("./paymentType");
	} 

	// Table type path
	public final class _Root_CarGroup
	{
		private static final Path _Root_CarGroup = _Root.add("CarGroup");
		public static Path getPathInSchema()
		{
			return _Root_CarGroup;
		}
		public static final Path _Root_CarGroup_CarGroupType = Path.parse("./carGroupType");
		public static final Path _Root_CarGroup_CarGroup = Path.parse("./carGroup");
		public static final Path _Root_CarGroup_Country = Path.parse("./country");
		public static final Path _Root_CarGroup__countryName = Path.parse("./_countryName");
		public static final Path _Root_CarGroup_Description = Path.parse("./description");
		public static final Path _Root_CarGroup_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_CarGroup_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_CarGroup_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_CarGroup_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_CarGroupType
	{
		private static final Path _Root_CarGroupType = _Root.add("CarGroupType");
		public static Path getPathInSchema()
		{
			return _Root_CarGroupType;
		}
		public static final Path _Root_CarGroupType_Base = Path.parse("./base");
		public static final Path _Root_CarGroupType_Base_Id = Path.parse("./base/id");
		public static final Path _Root_CarGroupType_Base_Name = Path.parse("./base/name");
		public static final Path _Root_CarGroupType_Base_Description = Path.parse("./base/description");
		public static final Path _Root_CarGroupType_GroupTypeOwner = Path.parse("./groupTypeOwner");
		public static final Path _Root_CarGroupType_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_CarGroupType_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_CarGroupType_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_CarGroupType_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Catalog
	{
		private static final Path _Root_Catalog = _Root.add("Catalog");
		public static Path getPathInSchema()
		{
			return _Root_Catalog;
		}
		public static final Path _Root_Catalog_Base = Path.parse("./base");
		public static final Path _Root_Catalog_Base_Id = Path.parse("./base/id");
		public static final Path _Root_Catalog_Base_Name = Path.parse("./base/name");
		public static final Path _Root_Catalog_Base_Description = Path.parse("./base/description");
		public static final Path _Root_Catalog_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_Catalog_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_Catalog_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_Catalog_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_ExteriorColor
	{
		private static final Path _Root_ExteriorColor = _Root.add("ExteriorColor");
		public static Path getPathInSchema()
		{
			return _Root_ExteriorColor;
		}
		public static final Path _Root_ExteriorColor_Base = Path.parse("./base");
		public static final Path _Root_ExteriorColor_Base_Id = Path.parse("./base/id");
		public static final Path _Root_ExteriorColor_Base_Name = Path.parse("./base/name");
		public static final Path _Root_ExteriorColor_Base_Description = Path.parse("./base/description");
		public static final Path _Root_ExteriorColor_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_ExteriorColor_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_ExteriorColor_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_ExteriorColor_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_InteriorColor
	{
		private static final Path _Root_InteriorColor = _Root.add("InteriorColor");
		public static Path getPathInSchema()
		{
			return _Root_InteriorColor;
		}
		public static final Path _Root_InteriorColor_Base = Path.parse("./base");
		public static final Path _Root_InteriorColor_Base_Id = Path.parse("./base/id");
		public static final Path _Root_InteriorColor_Base_Name = Path.parse("./base/name");
		public static final Path _Root_InteriorColor_Base_Description = Path.parse("./base/description");
		public static final Path _Root_InteriorColor_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_InteriorColor_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_InteriorColor_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_InteriorColor_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_HighlightCategoryConfig
	{
		private static final Path _Root_HighlightCategoryConfig = _Root.add("HighlightCategoryConfig");
		public static Path getPathInSchema()
		{
			return _Root_HighlightCategoryConfig;
		}
		public static final Path _Root_HighlightCategoryConfig_HighlightName = Path.parse("./highlightName");
		public static final Path _Root_HighlightCategoryConfig_Catalog = Path.parse("./catalog");
		public static final Path _Root_HighlightCategoryConfig_Category = Path.parse("./category");
	} 

	// Table type path
	public final class _Root_HighlightName
	{
		private static final Path _Root_HighlightName = _Root.add("HighlightName");
		public static Path getPathInSchema()
		{
			return _Root_HighlightName;
		}
		public static final Path _Root_HighlightName_Base = Path.parse("./base");
		public static final Path _Root_HighlightName_Base_Id = Path.parse("./base/id");
		public static final Path _Root_HighlightName_Base_Name = Path.parse("./base/name");
		public static final Path _Root_HighlightName_Base_Description = Path.parse("./base/description");
		public static final Path _Root_HighlightName_HighlightType = Path.parse("./highlightType");
		public static final Path _Root_HighlightName_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_HighlightName_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_HighlightName_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_HighlightName_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_HighlightTechspecConfig
	{
		private static final Path _Root_HighlightTechspecConfig = _Root.add("HighlightTechspecConfig");
		public static Path getPathInSchema()
		{
			return _Root_HighlightTechspecConfig;
		}
		public static final Path _Root_HighlightTechspecConfig_HighlightName = Path.parse("./highlightName");
		public static final Path _Root_HighlightTechspecConfig_Catalog = Path.parse("./catalog");
		public static final Path _Root_HighlightTechspecConfig_TechTitle = Path.parse("./techTitle");
	} 

	// Table type path
	public final class _Root_HighlightType
	{
		private static final Path _Root_HighlightType = _Root.add("HighlightType");
		public static Path getPathInSchema()
		{
			return _Root_HighlightType;
		}
		public static final Path _Root_HighlightType_Base = Path.parse("./base");
		public static final Path _Root_HighlightType_Base_Id = Path.parse("./base/id");
		public static final Path _Root_HighlightType_Base_Name = Path.parse("./base/name");
		public static final Path _Root_HighlightType_Base_Description = Path.parse("./base/description");
		public static final Path _Root_HighlightType_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_HighlightType_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_HighlightType_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_HighlightType_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Make
	{
		private static final Path _Root_Make = _Root.add("Make");
		public static Path getPathInSchema()
		{
			return _Root_Make;
		}
		public static final Path _Root_Make_Base = Path.parse("./base");
		public static final Path _Root_Make_Base_Id = Path.parse("./base/id");
		public static final Path _Root_Make_Base_Name = Path.parse("./base/name");
		public static final Path _Root_Make_Base_Description = Path.parse("./base/description");
		public static final Path _Root_Make_Manufacturer = Path.parse("./manufacturer");
		public static final Path _Root_Make_Division = Path.parse("./division");
		public static final Path _Root_Make_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_Make_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_Make_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_Make_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_RoofColor
	{
		private static final Path _Root_RoofColor = _Root.add("RoofColor");
		public static Path getPathInSchema()
		{
			return _Root_RoofColor;
		}
		public static final Path _Root_RoofColor_Base = Path.parse("./base");
		public static final Path _Root_RoofColor_Base_Id = Path.parse("./base/id");
		public static final Path _Root_RoofColor_Base_Name = Path.parse("./base/name");
		public static final Path _Root_RoofColor_Base_Description = Path.parse("./base/description");
		public static final Path _Root_RoofColor_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_RoofColor_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_RoofColor_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_RoofColor_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_SeatType
	{
		private static final Path _Root_SeatType = _Root.add("SeatType");
		public static Path getPathInSchema()
		{
			return _Root_SeatType;
		}
		public static final Path _Root_SeatType_Base = Path.parse("./base");
		public static final Path _Root_SeatType_Base_Id = Path.parse("./base/id");
		public static final Path _Root_SeatType_Base_Name = Path.parse("./base/name");
		public static final Path _Root_SeatType_Base_Description = Path.parse("./base/description");
		public static final Path _Root_SeatType_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_SeatType_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_SeatType_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_SeatType_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Sipp
	{
		private static final Path _Root_Sipp = _Root.add("Sipp");
		public static Path getPathInSchema()
		{
			return _Root_Sipp;
		}
		public static final Path _Root_Sipp_SippCode = Path.parse("./sippCode");
		public static final Path _Root_Sipp_Category = Path.parse("./category");
		public static final Path _Root_Sipp__categoryDescription = Path.parse("./_categoryDescription");
		public static final Path _Root_Sipp_Type = Path.parse("./type");
		public static final Path _Root_Sipp__typeDescription = Path.parse("./_typeDescription");
		public static final Path _Root_Sipp_TransmissionDrive = Path.parse("./transmissionDrive");
		public static final Path _Root_Sipp__transmissionDriveDescription = Path.parse("./_transmissionDriveDescription");
		public static final Path _Root_Sipp_FuelAirConditioning = Path.parse("./fuelAirConditioning");
		public static final Path _Root_Sipp__fuelAirConditioningDescription = Path.parse("./_fuelAirConditioningDescription");
		public static final Path _Root_Sipp_Description = Path.parse("./description");
		public static final Path _Root_Sipp_SIPPCarClassRelationship = Path.parse("./SIPPCarClassRelationship");
		public static final Path _Root_Sipp_SIPPCarGroupRelationship = Path.parse("./SIPPCarGroupRelationship");
		public static final Path _Root_Sipp_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_Sipp_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_Sipp_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_Sipp_IsRecordActive = Path.parse("./isRecordActive");
	} 
	public static final Path _Root_SIPPData = _Root.add("SIPPData");

	// Table type path
	public final class _Root_SIPPData_SIPPCategory
	{
		private static final Path _Root_SIPPData_SIPPCategory = _Root_SIPPData.add("SIPPCategory");
		public static Path getPathInSchema()
		{
			return _Root_SIPPData_SIPPCategory;
		}
		public static final Path _Root_SIPPData_SIPPCategory_CategoryCode = Path.parse("./categoryCode");
		public static final Path _Root_SIPPData_SIPPCategory_Description = Path.parse("./description");
		public static final Path _Root_SIPPData_SIPPCategory_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_SIPPData_SIPPCategory_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_SIPPData_SIPPCategory_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_SIPPData_SIPPCategory_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_SIPPData_SIPPFuelAirConditioning
	{
		private static final Path _Root_SIPPData_SIPPFuelAirConditioning = _Root_SIPPData.add("SIPPFuelAirConditioning");
		public static Path getPathInSchema()
		{
			return _Root_SIPPData_SIPPFuelAirConditioning;
		}
		public static final Path _Root_SIPPData_SIPPFuelAirConditioning_FuelAirConditioningCode = Path.parse("./fuelAirConditioningCode");
		public static final Path _Root_SIPPData_SIPPFuelAirConditioning_Description = Path.parse("./description");
		public static final Path _Root_SIPPData_SIPPFuelAirConditioning_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_SIPPData_SIPPFuelAirConditioning_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_SIPPData_SIPPFuelAirConditioning_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_SIPPData_SIPPFuelAirConditioning_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_SIPPData_SIPPType
	{
		private static final Path _Root_SIPPData_SIPPType = _Root_SIPPData.add("SIPPType");
		public static Path getPathInSchema()
		{
			return _Root_SIPPData_SIPPType;
		}
		public static final Path _Root_SIPPData_SIPPType_TypeCode = Path.parse("./typeCode");
		public static final Path _Root_SIPPData_SIPPType_Description = Path.parse("./description");
		public static final Path _Root_SIPPData_SIPPType_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_SIPPData_SIPPType_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_SIPPData_SIPPType_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_SIPPData_SIPPType_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_SIPPData_SIPPTransmissionDrive
	{
		private static final Path _Root_SIPPData_SIPPTransmissionDrive = _Root_SIPPData.add("SIPPTransmissionDrive");
		public static Path getPathInSchema()
		{
			return _Root_SIPPData_SIPPTransmissionDrive;
		}
		public static final Path _Root_SIPPData_SIPPTransmissionDrive_TransmissionDriveCode = Path.parse("./transmissionDriveCode");
		public static final Path _Root_SIPPData_SIPPTransmissionDrive_Description = Path.parse("./description");
		public static final Path _Root_SIPPData_SIPPTransmissionDrive_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_SIPPData_SIPPTransmissionDrive_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_SIPPData_SIPPTransmissionDrive_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_SIPPData_SIPPTransmissionDrive_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_SIPPData_SIPPCarClassRelationship
	{
		private static final Path _Root_SIPPData_SIPPCarClassRelationship = _Root_SIPPData.add("SIPPCarClassRelationship");
		public static Path getPathInSchema()
		{
			return _Root_SIPPData_SIPPCarClassRelationship;
		}
		public static final Path _Root_SIPPData_SIPPCarClassRelationship_SippCode = Path.parse("./sippCode");
		public static final Path _Root_SIPPData_SIPPCarClassRelationship_CarClass = Path.parse("./carClass");
		public static final Path _Root_SIPPData_SIPPCarClassRelationship__carClass = Path.parse("./_carClass");
		public static final Path _Root_SIPPData_SIPPCarClassRelationship__countryName = Path.parse("./_countryName");
		public static final Path _Root_SIPPData_SIPPCarClassRelationship_Reservable = Path.parse("./reservable");
		public static final Path _Root_SIPPData_SIPPCarClassRelationship_ExactModel = Path.parse("./exactModel");
		public static final Path _Root_SIPPData_SIPPCarClassRelationship_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_SIPPData_SIPPCarClassRelationship_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_SIPPData_SIPPCarClassRelationship_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_SIPPData_SIPPCarClassRelationship_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_SIPPData_SIPPCarGroupRelationship
	{
		private static final Path _Root_SIPPData_SIPPCarGroupRelationship = _Root_SIPPData.add("SIPPCarGroupRelationship");
		public static Path getPathInSchema()
		{
			return _Root_SIPPData_SIPPCarGroupRelationship;
		}
		public static final Path _Root_SIPPData_SIPPCarGroupRelationship_SippCode = Path.parse("./sippCode");
		public static final Path _Root_SIPPData_SIPPCarGroupRelationship_CarGroup = Path.parse("./carGroup");
		public static final Path _Root_SIPPData_SIPPCarGroupRelationship__carGroupType = Path.parse("./_carGroupType");
		public static final Path _Root_SIPPData_SIPPCarGroupRelationship__carGroup = Path.parse("./_carGroup");
		public static final Path _Root_SIPPData_SIPPCarGroupRelationship__countryName = Path.parse("./_countryName");
		public static final Path _Root_SIPPData_SIPPCarGroupRelationship_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_SIPPData_SIPPCarGroupRelationship_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_SIPPData_SIPPCarGroupRelationship_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_SIPPData_SIPPCarGroupRelationship_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_SIPPData_PseudoCarCode
	{
		private static final Path _Root_SIPPData_PseudoCarCode = _Root_SIPPData.add("PseudoCarCode");
		public static Path getPathInSchema()
		{
			return _Root_SIPPData_PseudoCarCode;
		}
		public static final Path _Root_SIPPData_PseudoCarCode_PseudoCarCode = Path.parse("./pseudoCarCode");
		public static final Path _Root_SIPPData_PseudoCarCode_Definition = Path.parse("./definition");
		public static final Path _Root_SIPPData_PseudoCarCode_Category = Path.parse("./category");
		public static final Path _Root_SIPPData_PseudoCarCode_Type = Path.parse("./type");
		public static final Path _Root_SIPPData_PseudoCarCode_TransmissionDrive = Path.parse("./transmissionDrive");
		public static final Path _Root_SIPPData_PseudoCarCode_FuelAirConditioning = Path.parse("./fuelAirConditioning");
		public static final Path _Root_SIPPData_PseudoCarCode_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_SIPPData_PseudoCarCode_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_SIPPData_PseudoCarCode_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_SIPPData_PseudoCarCode_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_VehicleColor
	{
		private static final Path _Root_VehicleColor = _Root.add("VehicleColor");
		public static Path getPathInSchema()
		{
			return _Root_VehicleColor;
		}
		public static final Path _Root_VehicleColor_Base = Path.parse("./base");
		public static final Path _Root_VehicleColor_Base_Id = Path.parse("./base/id");
		public static final Path _Root_VehicleColor_Base_Name = Path.parse("./base/name");
		public static final Path _Root_VehicleColor_Base_Description = Path.parse("./base/description");
		public static final Path _Root_VehicleColor_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_VehicleColor_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_VehicleColor_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_VehicleColor_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_WheelDrive
	{
		private static final Path _Root_WheelDrive = _Root.add("WheelDrive");
		public static Path getPathInSchema()
		{
			return _Root_WheelDrive;
		}
		public static final Path _Root_WheelDrive_Base = Path.parse("./base");
		public static final Path _Root_WheelDrive_Base_Id = Path.parse("./base/id");
		public static final Path _Root_WheelDrive_Base_Name = Path.parse("./base/name");
		public static final Path _Root_WheelDrive_Base_Description = Path.parse("./base/description");
		public static final Path _Root_WheelDrive_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_WheelDrive_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_WheelDrive_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_WheelDrive_IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_MDMVehicleReferenceCrossReference
	{
		private static final Path _Root_MDMVehicleReferenceCrossReference = _Root.add("MDMVehicleReferenceCrossReference");
		public static Path getPathInSchema()
		{
			return _Root_MDMVehicleReferenceCrossReference;
		}
		public static final Path _Root_MDMVehicleReferenceCrossReference_Base = Path.parse("./base");
		public static final Path _Root_MDMVehicleReferenceCrossReference_Base_Id = Path.parse("./base/id");
		public static final Path _Root_MDMVehicleReferenceCrossReference_Base_Name = Path.parse("./base/name");
		public static final Path _Root_MDMVehicleReferenceCrossReference_Base_Description = Path.parse("./base/description");
		public static final Path _Root_MDMVehicleReferenceCrossReference_EbxReplicationTableName = Path.parse("./ebxReplicationTableName");
		public static final Path _Root_MDMVehicleReferenceCrossReference_EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _Root_MDMVehicleReferenceCrossReference_EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _Root_MDMVehicleReferenceCrossReference_EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _Root_MDMVehicleReferenceCrossReference_IsRecordActive = Path.parse("./isRecordActive");
	} 
	// ===============================================

}
