package com.hertz.mdm.vehicle.path;

import com.orchestranetworks.schema.Path;
/**
 * Generated by EBX5 5.7.1 fix B [1034:0005], at  2017/09/13 09:26:13 [EDT].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: hertz-mdm, path: /WEB-INF/ebx/schemas/VehicleDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface VehiclePaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Prefix:  ''.
	// Statistics:
	//		362 path constants.
	//		236 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Vehicle {
		private static final Path _Root_Vehicle = _Root.add("Vehicle");
		public static Path getPathInSchema()
		{
			return _Root_Vehicle;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _DaqaMetaData = Path.parse("./DaqaMetaData");
	public static final Path _DaqaMetaData_State = Path.parse("./DaqaMetaData/State");
	public static final Path _DaqaMetaData_ClusterId = Path.parse("./DaqaMetaData/ClusterId");
	public static final Path _DaqaMetaData_Score = Path.parse("./DaqaMetaData/Score");
	public static final Path _DaqaMetaData_ScoreFirstMatching = Path.parse("./DaqaMetaData/ScoreFirstMatching");
	public static final Path _DaqaMetaData_ScoreSecondMatching = Path.parse("./DaqaMetaData/ScoreSecondMatching");
	public static final Path _DaqaMetaData_FieldScores = Path.parse("./DaqaMetaData/fieldScores");
	public static final Path _DaqaMetaData_FieldScores_Field = Path.parse("./DaqaMetaData/fieldScores/Field");
	public static final Path _DaqaMetaData_FieldScores_Score = Path.parse("./DaqaMetaData/fieldScores/Score");
	public static final Path _DaqaMetaData_FieldScores_ScoreFirstMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreFirstMatching");
	public static final Path _DaqaMetaData_FieldScores_ScoreSecondMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreSecondMatching");
	public static final Path _DaqaMetaData_SimpleMatchingScore = Path.parse("./DaqaMetaData/simpleMatchingScore");
	public static final Path _DaqaMetaData_TargetRecord = Path.parse("./DaqaMetaData/TargetRecord");
	public static final Path _DaqaMetaData_MergeOrigin = Path.parse("./DaqaMetaData/MergeOrigin");
	public static final Path _DaqaMetaData_Timestamp = Path.parse("./DaqaMetaData/Timestamp");
	public static final Path _DaqaMetaData_WasGolden = Path.parse("./DaqaMetaData/WasGolden");
	public static final Path _DaqaMetaData_ListOfNotSuspects = Path.parse("./DaqaMetaData/listOfNotSuspects");
	public static final Path _DaqaMetaData_ListOfNotSuspects_NotSuspectWith = Path.parse("./DaqaMetaData/listOfNotSuspects/NotSuspectWith");
	public static final Path _DaqaMetaData_ListOfNotSuspects_Score = Path.parse("./DaqaMetaData/listOfNotSuspects/Score");
	public static final Path _DaqaMetaData_GroupAtOnce = Path.parse("./DaqaMetaData/groupAtOnce");
	public static final Path _DaqaMetaData_GroupAtOnce_Grouped = Path.parse("./DaqaMetaData/groupAtOnce/grouped");
	public static final Path _DaqaMetaData_GroupAtOnce_ClusterSize = Path.parse("./DaqaMetaData/groupAtOnce/clusterSize");
	public static final Path _DaqaMetaData_Workflow = Path.parse("./DaqaMetaData/workflow");
	public static final Path _DaqaMetaData_Workflow_Uuid = Path.parse("./DaqaMetaData/workflow/Uuid");
	public static final Path _DaqaMetaData_Workflow_Name = Path.parse("./DaqaMetaData/workflow/Name");
	public static final Path _DaqaMetaData_Workflow_Timestamp = Path.parse("./DaqaMetaData/workflow/Timestamp");
	public static final Path _DaqaMetaData_Workflow_User = Path.parse("./DaqaMetaData/workflow/User");
	public static final Path _DaqaMetaData_ProcessPolicyCode = Path.parse("./DaqaMetaData/ProcessPolicyCode");
	public static final Path _DaqaMetaData_MatchingPolicyCode = Path.parse("./DaqaMetaData/MatchingPolicyCode");
	public static final Path _DaqaMetaData_SurvivorshipPolicyCode = Path.parse("./DaqaMetaData/SurvivorshipPolicyCode");
	public static final Path _DaqaMetaData_OperationCode = Path.parse("./DaqaMetaData/OperationCode");
	public static final Path _DaqaMetaData_DateOfLastOperationCode = Path.parse("./DaqaMetaData/DateOfLastOperationCode");
	public static final Path _DaqaMetaData_BatchOperationCode = Path.parse("./DaqaMetaData/BatchOperationCode");
	public static final Path _DaqaMetaData_CleansingMetadata = Path.parse("./DaqaMetaData/CleansingMetadata");
	public static final Path _DaqaMetaData_CleansingMetadata_CleansingState = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingState");
	public static final Path _DaqaMetaData_CleansingMetadata_CleansingProcedureCode = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingProcedureCode");
	public static final Path _DaqaMetaData_CleansingMetadata_CleansingOperation = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingOperation");
	public static final Path _DaqaMetaData_CleansingMetadata_ExecutionDate = Path.parse("./DaqaMetaData/CleansingMetadata/ExecutionDate");
	public static final Path _DaqaMetaData_CleansingMetadata_User = Path.parse("./DaqaMetaData/CleansingMetadata/User");
	public static final Path _DaqaMetaData_CleansingMetadata_Field = Path.parse("./DaqaMetaData/CleansingMetadata/Field");
	public static final Path _DaqaMetaData_CleansingMetadata_QualityDefect = Path.parse("./DaqaMetaData/CleansingMetadata/QualityDefect");
	public static final Path _DaqaMetaData_FieldMergedLogging = Path.parse("./DaqaMetaData/fieldMergedLogging");
	public static final Path _DaqaMetaData_FieldMergedLogging_DateFieldMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/dateFieldMerged");
	public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedLogicalName = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedLogicalName");
	public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedValue = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedValue");
	public static final Path _DaqaMetaData_FieldMergedLogging_FieldTargetValueBeforeMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldTargetValueBeforeMerged");
	public static final Path _DaqaMetaData_FieldMergedLogging_SurvivorshipFunctionCode = Path.parse("./DaqaMetaData/fieldMergedLogging/survivorshipFunctionCode");
	public static final Path _DaqaMetaData_FieldMergedLogging_PrimaryKeyMergedRecord = Path.parse("./DaqaMetaData/fieldMergedLogging/primaryKeyMergedRecord");
	public static final Path _SourceSystem = Path.parse("./sourceSystem");
	public static final Path _VehicleIdentificationNumber = Path.parse("./vehicleIdentificationNumber");
	public static final Path _BuildYear = Path.parse("./buildYear");
	public static final Path _VehicleDescription = Path.parse("./vehicleDescription");
	public static final Path _DoorCount = Path.parse("./doorCount");
	public static final Path _EngineCylinders = Path.parse("./EngineCylinders");
	public static final Path _Model = Path.parse("./model");
	public static final Path _OwningCountry = Path.parse("./owningCountry");
	public static final Path _SeatType = Path.parse("./seatType");
	public static final Path _Sipp = Path.parse("./sipp");
	public static final Path _SippFirstTwoDigits = Path.parse("./sippFirstTwoDigits");
	public static final Path _WheelDrive = Path.parse("./wheelDrive");
	public static final Path _Colors = Path.parse("./Colors");
	public static final Path _Colors_ExteriorColor = Path.parse("./Colors/exteriorColor");
	public static final Path _Colors_InteriorColor = Path.parse("./Colors/interiorColor");
	public static final Path _Colors_RoofColor = Path.parse("./Colors/roofColor");
	public static final Path _Colors_VehicleColor = Path.parse("./Colors/vehicleColor");
	public static final Path _Features = Path.parse("./Features");
	public static final Path _Features_HasABSBrakes = Path.parse("./Features/hasABSBrakes");
	public static final Path _Features_HasAirConditioning = Path.parse("./Features/hasAirConditioning");
	public static final Path _Features_HasAntiTheftOption = Path.parse("./Features/hasAntiTheftOption");
	public static final Path _Features_HasAutomaticTransmission = Path.parse("./Features/hasAutomaticTransmission");
	public static final Path _Features_HasClothSeats = Path.parse("./Features/hasClothSeats");
	public static final Path _Features_HasCruiseControl = Path.parse("./Features/hasCruiseControl");
	public static final Path _Features_HasDriverAirbag = Path.parse("./Features/hasDriverAirbag");
	public static final Path _Features_HasNeverLost = Path.parse("./Features/hasNeverLost");
	public static final Path _Features_HasPassengerAirbag = Path.parse("./Features/hasPassengerAirbag");
	public static final Path _Features_HasPowerLocks = Path.parse("./Features/hasPowerLocks");
	public static final Path _Features_HasPowerSeats = Path.parse("./Features/hasPowerSeats");
	public static final Path _Features_HasPowerWindows = Path.parse("./Features/hasPowerWindows");
	public static final Path _Features_HasRadio = Path.parse("./Features/hasRadio");
	public static final Path _Features_HasRearAirbag = Path.parse("./Features/hasRearAirbag");
	public static final Path _Features_HasSatelliteRadio = Path.parse("./Features/hasSatelliteRadio");
	public static final Path _Features_HasSideAirbag = Path.parse("./Features/hasSideAirbag");
	public static final Path _Features_HasSunroof = Path.parse("./Features/hasSunroof");
	public static final Path _Features_HasTiltWheel = Path.parse("./Features/hasTiltWheel");
	public static final Path _Features_HasZibox = Path.parse("./Features/hasZibox");
	public static final Path _Codes = Path.parse("./Codes");
	public static final Path _Codes_EngineCode = Path.parse("./Codes/engineCode");
	public static final Path _Codes_IgnitionKeyCode = Path.parse("./Codes/ignitionKeyCode");
	public static final Path _Codes_KeylessCode = Path.parse("./Codes/keylessCode");
	public static final Path _Codes_TransmissionCode = Path.parse("./Codes/transmissionCode");
	public static final Path _Codes_TollPassCode = Path.parse("./Codes/tollPassCode");
	public static final Path _Codes_TrunkKeyCode = Path.parse("./Codes/trunkKeyCode");
	public static final Path _Highlights = Path.parse("./Highlights");
	public static final Path _VehicleAssets = Path.parse("./VehicleAssets");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	public static final Path _Root_VehicleData = _Root.add("VehicleData");

	// Table type path
	public final class _Root_VehicleData_CatalogVehicle {
		private static final Path _Root_VehicleData_CatalogVehicle = _Root_VehicleData.add("CatalogVehicle");
		public static Path getPathInSchema()
		{
			return _Root_VehicleData_CatalogVehicle;
		}
	public static final Path _VehicleIdentificationNumber = Path.parse("./vehicleIdentificationNumber");
	public static final Path _StyleID = Path.parse("./styleID");
	public static final Path _Color = Path.parse("./color");
	public static final Path _OptionPrices = Path.parse("./optionPrices");
	public static final Path _TechSpecs = Path.parse("./techSpecs");
	public static final Path _Categories = Path.parse("./categories");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_VehicleData_CatalogVehicleOption {
		private static final Path _Root_VehicleData_CatalogVehicleOption = _Root_VehicleData.add("CatalogVehicleOption");
		public static Path getPathInSchema()
		{
			return _Root_VehicleData_CatalogVehicleOption;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _CatalogVehicle = Path.parse("./catalogVehicle");
	public static final Path _Option = Path.parse("./option");
	public static final Path __style_ID = Path.parse("./_style_ID");
	public static final Path _OemCode = Path.parse("./oemCode");
	public static final Path _AltOptionCode = Path.parse("./altOptionCode");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	public static final Path _Root_VehicleData_CatalogVehicleData = _Root_VehicleData.add("CatalogVehicleData");

	// Table type path
	public final class _Root_VehicleData_CatalogVehicleData_CatalogVehicleOptionPriceRelationship {
		private static final Path _Root_VehicleData_CatalogVehicleData_CatalogVehicleOptionPriceRelationship = _Root_VehicleData_CatalogVehicleData.add("CatalogVehicleOptionPriceRelationship");
		public static Path getPathInSchema()
		{
			return _Root_VehicleData_CatalogVehicleData_CatalogVehicleOptionPriceRelationship;
		}
	public static final Path _CatalogVehicle = Path.parse("./catalogVehicle");
	public static final Path _Price = Path.parse("./price");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_VehicleData_CatalogVehicleData_CatalogVehicleTechSpecRelationship {
		private static final Path _Root_VehicleData_CatalogVehicleData_CatalogVehicleTechSpecRelationship = _Root_VehicleData_CatalogVehicleData.add("CatalogVehicleTechSpecRelationship");
		public static Path getPathInSchema()
		{
			return _Root_VehicleData_CatalogVehicleData_CatalogVehicleTechSpecRelationship;
		}
	public static final Path _CatalogVehicle = Path.parse("./catalogVehicle");
	public static final Path _TechSpec = Path.parse("./techSpec");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_VehicleData_CatalogVehicleData_CatalogVehicleCategoryRelationship {
		private static final Path _Root_VehicleData_CatalogVehicleData_CatalogVehicleCategoryRelationship = _Root_VehicleData_CatalogVehicleData.add("CatalogVehicleCategoryRelationship");
		public static Path getPathInSchema()
		{
			return _Root_VehicleData_CatalogVehicleData_CatalogVehicleCategoryRelationship;
		}
	public static final Path _CatalogVehicle = Path.parse("./catalogVehicle");
	public static final Path _Category = Path.parse("./category");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_VehicleData_VehicleAsset {
		private static final Path _Root_VehicleData_VehicleAsset = _Root_VehicleData.add("VehicleAsset");
		public static Path getPathInSchema()
		{
			return _Root_VehicleData_VehicleAsset;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _DaqaMetaData = Path.parse("./DaqaMetaData");
	public static final Path _DaqaMetaData_State = Path.parse("./DaqaMetaData/State");
	public static final Path _DaqaMetaData_ClusterId = Path.parse("./DaqaMetaData/ClusterId");
	public static final Path _DaqaMetaData_Score = Path.parse("./DaqaMetaData/Score");
	public static final Path _DaqaMetaData_ScoreFirstMatching = Path.parse("./DaqaMetaData/ScoreFirstMatching");
	public static final Path _DaqaMetaData_ScoreSecondMatching = Path.parse("./DaqaMetaData/ScoreSecondMatching");
	public static final Path _DaqaMetaData_FieldScores = Path.parse("./DaqaMetaData/fieldScores");
	public static final Path _DaqaMetaData_FieldScores_Field = Path.parse("./DaqaMetaData/fieldScores/Field");
	public static final Path _DaqaMetaData_FieldScores_Score = Path.parse("./DaqaMetaData/fieldScores/Score");
	public static final Path _DaqaMetaData_FieldScores_ScoreFirstMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreFirstMatching");
	public static final Path _DaqaMetaData_FieldScores_ScoreSecondMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreSecondMatching");
	public static final Path _DaqaMetaData_SimpleMatchingScore = Path.parse("./DaqaMetaData/simpleMatchingScore");
	public static final Path _DaqaMetaData_TargetRecord = Path.parse("./DaqaMetaData/TargetRecord");
	public static final Path _DaqaMetaData_MergeOrigin = Path.parse("./DaqaMetaData/MergeOrigin");
	public static final Path _DaqaMetaData_Timestamp = Path.parse("./DaqaMetaData/Timestamp");
	public static final Path _DaqaMetaData_WasGolden = Path.parse("./DaqaMetaData/WasGolden");
	public static final Path _DaqaMetaData_ListOfNotSuspects = Path.parse("./DaqaMetaData/listOfNotSuspects");
	public static final Path _DaqaMetaData_ListOfNotSuspects_NotSuspectWith = Path.parse("./DaqaMetaData/listOfNotSuspects/NotSuspectWith");
	public static final Path _DaqaMetaData_ListOfNotSuspects_Score = Path.parse("./DaqaMetaData/listOfNotSuspects/Score");
	public static final Path _DaqaMetaData_GroupAtOnce = Path.parse("./DaqaMetaData/groupAtOnce");
	public static final Path _DaqaMetaData_GroupAtOnce_Grouped = Path.parse("./DaqaMetaData/groupAtOnce/grouped");
	public static final Path _DaqaMetaData_GroupAtOnce_ClusterSize = Path.parse("./DaqaMetaData/groupAtOnce/clusterSize");
	public static final Path _DaqaMetaData_Workflow = Path.parse("./DaqaMetaData/workflow");
	public static final Path _DaqaMetaData_Workflow_Uuid = Path.parse("./DaqaMetaData/workflow/Uuid");
	public static final Path _DaqaMetaData_Workflow_Name = Path.parse("./DaqaMetaData/workflow/Name");
	public static final Path _DaqaMetaData_Workflow_Timestamp = Path.parse("./DaqaMetaData/workflow/Timestamp");
	public static final Path _DaqaMetaData_Workflow_User = Path.parse("./DaqaMetaData/workflow/User");
	public static final Path _DaqaMetaData_ProcessPolicyCode = Path.parse("./DaqaMetaData/ProcessPolicyCode");
	public static final Path _DaqaMetaData_MatchingPolicyCode = Path.parse("./DaqaMetaData/MatchingPolicyCode");
	public static final Path _DaqaMetaData_SurvivorshipPolicyCode = Path.parse("./DaqaMetaData/SurvivorshipPolicyCode");
	public static final Path _DaqaMetaData_OperationCode = Path.parse("./DaqaMetaData/OperationCode");
	public static final Path _DaqaMetaData_DateOfLastOperationCode = Path.parse("./DaqaMetaData/DateOfLastOperationCode");
	public static final Path _DaqaMetaData_BatchOperationCode = Path.parse("./DaqaMetaData/BatchOperationCode");
	public static final Path _DaqaMetaData_CleansingMetadata = Path.parse("./DaqaMetaData/CleansingMetadata");
	public static final Path _DaqaMetaData_CleansingMetadata_CleansingState = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingState");
	public static final Path _DaqaMetaData_CleansingMetadata_CleansingProcedureCode = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingProcedureCode");
	public static final Path _DaqaMetaData_CleansingMetadata_CleansingOperation = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingOperation");
	public static final Path _DaqaMetaData_CleansingMetadata_ExecutionDate = Path.parse("./DaqaMetaData/CleansingMetadata/ExecutionDate");
	public static final Path _DaqaMetaData_CleansingMetadata_User = Path.parse("./DaqaMetaData/CleansingMetadata/User");
	public static final Path _DaqaMetaData_CleansingMetadata_Field = Path.parse("./DaqaMetaData/CleansingMetadata/Field");
	public static final Path _DaqaMetaData_CleansingMetadata_QualityDefect = Path.parse("./DaqaMetaData/CleansingMetadata/QualityDefect");
	public static final Path _DaqaMetaData_FieldMergedLogging = Path.parse("./DaqaMetaData/fieldMergedLogging");
	public static final Path _DaqaMetaData_FieldMergedLogging_DateFieldMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/dateFieldMerged");
	public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedLogicalName = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedLogicalName");
	public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedValue = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedValue");
	public static final Path _DaqaMetaData_FieldMergedLogging_FieldTargetValueBeforeMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldTargetValueBeforeMerged");
	public static final Path _DaqaMetaData_FieldMergedLogging_SurvivorshipFunctionCode = Path.parse("./DaqaMetaData/fieldMergedLogging/survivorshipFunctionCode");
	public static final Path _DaqaMetaData_FieldMergedLogging_PrimaryKeyMergedRecord = Path.parse("./DaqaMetaData/fieldMergedLogging/primaryKeyMergedRecord");
	public static final Path _SourceSystem = Path.parse("./sourceSystem");
	public static final Path _AssetTag = Path.parse("./assetTag");
	public static final Path _Area = Path.parse("./area");
	public static final Path _UnitNumber = Path.parse("./unitNumber");
	public static final Path _VehicleIdentificationNumber = Path.parse("./vehicleIdentificationNumber");
	public static final Path _VehicleFkey = Path.parse("./vehicleFkey");
	public static final Path _LicenseRegistrationCountry = Path.parse("./licenseRegistrationCountry");
	public static final Path _LicenseRegistrationState = Path.parse("./licenseRegistrationState");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_VehicleData_VehicleVehicleHighlightsRelationship {
		private static final Path _Root_VehicleData_VehicleVehicleHighlightsRelationship = _Root_VehicleData.add("VehicleVehicleHighlightsRelationship");
		public static Path getPathInSchema()
		{
			return _Root_VehicleData_VehicleVehicleHighlightsRelationship;
		}
	public static final Path _VehicleIdentificationNumber = Path.parse("./vehicleIdentificationNumber");
	public static final Path _VehicleHighlight = Path.parse("./vehicleHighlight");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Model {
		private static final Path _Root_Model = _Root.add("Model");
		public static Path getPathInSchema()
		{
			return _Root_Model;
		}
	public static final Path _Model = Path.parse("./model");
	public static final Path _ModelStyle = Path.parse("./modelStyle");
	public static final Path _DoorCount = Path.parse("./doorCount");
	public static final Path _Description = Path.parse("./description");
	public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
	public static final Path _ModelGroup = Path.parse("./modelGroup");
	public static final Path _Make = Path.parse("./make");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Test {
		private static final Path _Root_Test = _Root.add("Test");
		public static Path getPathInSchema()
		{
			return _Root_Test;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _DaqaMetaData = Path.parse("./DaqaMetaData");
	public static final Path _DaqaMetaData_State = Path.parse("./DaqaMetaData/State");
	public static final Path _DaqaMetaData_ClusterId = Path.parse("./DaqaMetaData/ClusterId");
	public static final Path _DaqaMetaData_Score = Path.parse("./DaqaMetaData/Score");
	public static final Path _DaqaMetaData_ScoreFirstMatching = Path.parse("./DaqaMetaData/ScoreFirstMatching");
	public static final Path _DaqaMetaData_ScoreSecondMatching = Path.parse("./DaqaMetaData/ScoreSecondMatching");
	public static final Path _DaqaMetaData_FieldScores = Path.parse("./DaqaMetaData/fieldScores");
	public static final Path _DaqaMetaData_FieldScores_Field = Path.parse("./DaqaMetaData/fieldScores/Field");
	public static final Path _DaqaMetaData_FieldScores_Score = Path.parse("./DaqaMetaData/fieldScores/Score");
	public static final Path _DaqaMetaData_FieldScores_ScoreFirstMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreFirstMatching");
	public static final Path _DaqaMetaData_FieldScores_ScoreSecondMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreSecondMatching");
	public static final Path _DaqaMetaData_SimpleMatchingScore = Path.parse("./DaqaMetaData/simpleMatchingScore");
	public static final Path _DaqaMetaData_TargetRecord = Path.parse("./DaqaMetaData/TargetRecord");
	public static final Path _DaqaMetaData_MergeOrigin = Path.parse("./DaqaMetaData/MergeOrigin");
	public static final Path _DaqaMetaData_Timestamp = Path.parse("./DaqaMetaData/Timestamp");
	public static final Path _DaqaMetaData_WasGolden = Path.parse("./DaqaMetaData/WasGolden");
	public static final Path _DaqaMetaData_ListOfNotSuspects = Path.parse("./DaqaMetaData/listOfNotSuspects");
	public static final Path _DaqaMetaData_ListOfNotSuspects_NotSuspectWith = Path.parse("./DaqaMetaData/listOfNotSuspects/NotSuspectWith");
	public static final Path _DaqaMetaData_ListOfNotSuspects_Score = Path.parse("./DaqaMetaData/listOfNotSuspects/Score");
	public static final Path _DaqaMetaData_GroupAtOnce = Path.parse("./DaqaMetaData/groupAtOnce");
	public static final Path _DaqaMetaData_GroupAtOnce_Grouped = Path.parse("./DaqaMetaData/groupAtOnce/grouped");
	public static final Path _DaqaMetaData_GroupAtOnce_ClusterSize = Path.parse("./DaqaMetaData/groupAtOnce/clusterSize");
	public static final Path _DaqaMetaData_Workflow = Path.parse("./DaqaMetaData/workflow");
	public static final Path _DaqaMetaData_Workflow_Uuid = Path.parse("./DaqaMetaData/workflow/Uuid");
	public static final Path _DaqaMetaData_Workflow_Name = Path.parse("./DaqaMetaData/workflow/Name");
	public static final Path _DaqaMetaData_Workflow_Timestamp = Path.parse("./DaqaMetaData/workflow/Timestamp");
	public static final Path _DaqaMetaData_Workflow_User = Path.parse("./DaqaMetaData/workflow/User");
	public static final Path _DaqaMetaData_ProcessPolicyCode = Path.parse("./DaqaMetaData/ProcessPolicyCode");
	public static final Path _DaqaMetaData_MatchingPolicyCode = Path.parse("./DaqaMetaData/MatchingPolicyCode");
	public static final Path _DaqaMetaData_SurvivorshipPolicyCode = Path.parse("./DaqaMetaData/SurvivorshipPolicyCode");
	public static final Path _DaqaMetaData_OperationCode = Path.parse("./DaqaMetaData/OperationCode");
	public static final Path _DaqaMetaData_DateOfLastOperationCode = Path.parse("./DaqaMetaData/DateOfLastOperationCode");
	public static final Path _DaqaMetaData_BatchOperationCode = Path.parse("./DaqaMetaData/BatchOperationCode");
	public static final Path _DaqaMetaData_CleansingMetadata = Path.parse("./DaqaMetaData/CleansingMetadata");
	public static final Path _DaqaMetaData_CleansingMetadata_CleansingState = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingState");
	public static final Path _DaqaMetaData_CleansingMetadata_CleansingProcedureCode = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingProcedureCode");
	public static final Path _DaqaMetaData_CleansingMetadata_CleansingOperation = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingOperation");
	public static final Path _DaqaMetaData_CleansingMetadata_ExecutionDate = Path.parse("./DaqaMetaData/CleansingMetadata/ExecutionDate");
	public static final Path _DaqaMetaData_CleansingMetadata_User = Path.parse("./DaqaMetaData/CleansingMetadata/User");
	public static final Path _DaqaMetaData_CleansingMetadata_Field = Path.parse("./DaqaMetaData/CleansingMetadata/Field");
	public static final Path _DaqaMetaData_CleansingMetadata_QualityDefect = Path.parse("./DaqaMetaData/CleansingMetadata/QualityDefect");
	public static final Path _DaqaMetaData_FieldMergedLogging = Path.parse("./DaqaMetaData/fieldMergedLogging");
	public static final Path _DaqaMetaData_FieldMergedLogging_DateFieldMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/dateFieldMerged");
	public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedLogicalName = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedLogicalName");
	public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedValue = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedValue");
	public static final Path _DaqaMetaData_FieldMergedLogging_FieldTargetValueBeforeMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldTargetValueBeforeMerged");
	public static final Path _DaqaMetaData_FieldMergedLogging_SurvivorshipFunctionCode = Path.parse("./DaqaMetaData/fieldMergedLogging/survivorshipFunctionCode");
	public static final Path _DaqaMetaData_FieldMergedLogging_PrimaryKeyMergedRecord = Path.parse("./DaqaMetaData/fieldMergedLogging/primaryKeyMergedRecord");
	public static final Path _System = Path.parse("./system");
	public static final Path _VIN = Path.parse("./VIN");
	public static final Path _Model = Path.parse("./model");
	public static final Path _SeatType = Path.parse("./seatType");
	public static final Path _DoorCount = Path.parse("./doorCount");
	} 
	// ===============================================

}
