package com.hertz.mdm.location.path;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX5 5.8.1 [1067], at  2018/01/16 11:37:23 [EST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: hertz-mdm, path: /WEB-INF/ebx/schemas/LocationDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface LocationPaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Prefix:  ''.
	// Statistics:
	//		1263 path constants.
	//		724 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_LocationProject
	{
		private static final Path _Root_LocationProject = _Root.add("LocationProject");
		public static Path getPathInSchema()
		{
			return _Root_LocationProject;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Name = Path.parse("./name");
		public static final Path _ProjectType = Path.parse("./projectType");
		public static final Path _Location = Path.parse("./location");
		public static final Path _ProjectStatus = Path.parse("./projectStatus");
		public static final Path _Region = Path.parse("./region");
		public static final Path __isOnAirport = Path.parse("./_isOnAirport");
		public static final Path _IsLocationServedBy = Path.parse("./isLocationServedBy");
		public static final Path _ServedBy = Path.parse("./servedBy");
		public static final Path _SatelliteParent = Path.parse("./satelliteParent");
		public static final Path __isCarSalesLocation = Path.parse("./_isCarSalesLocation");
		public static final Path _MeasurementSystem = Path.parse("./measurementSystem");
		public static final Path _IsAreaAssigned = Path.parse("./isAreaAssigned");
		public static final Path _AreaNumber = Path.parse("./areaNumber");
		public static final Path _RequiresITQuestionnaire = Path.parse("./requiresITQuestionnaire");
		public static final Path _IsLocationNumberAssigned = Path.parse("./isLocationNumberAssigned");
		public static final Path _RequiresEnvironmentalAffairsApproval = Path.parse("./requiresEnvironmentalAffairsApproval");
		public static final Path _IsLE = Path.parse("./isLE");
		public static final Path __isAutomated = Path.parse("./_isAutomated");
		public static final Path __isStaffed = Path.parse("./_isStaffed");
		public static final Path _IsStaffedByHertzPersonnel = Path.parse("./isStaffedByHertzPersonnel");
		public static final Path __isInPlant = Path.parse("./_isInPlant");
		public static final Path _ProjectOriginator = Path.parse("./projectOriginator");
		public static final Path _CancelDate = Path.parse("./cancelDate");
		public static final Path _CancelReason = Path.parse("./cancelReason");
		public static final Path _ProjectExpirationDate = Path.parse("./projectExpirationDate");
		public static final Path _ProjectedCloseDateChanged = Path.parse("./projectedCloseDateChanged");
		public static final Path _RequiredRestorations = Path.parse("./requiredRestorations");
		public static final Path _IsRestorationRequired = Path.parse("./isRestorationRequired");
		public static final Path _IsTempCloseRequired = Path.parse("./isTempCloseRequired");
		public static final Path _DoesLocationHaveCopiersPrinters = Path.parse("./doesLocationHaveCopiersPrinters");
		public static final Path _OpenLocation = Path.parse("./OpenLocation");
		public static final Path _OpenLocation_ActualOpenDate = Path.parse("./OpenLocation/actualOpenDate");
		public static final Path _OpenLocation_ProjectedOpenDate = Path.parse("./OpenLocation/projectedOpenDate");
		public static final Path _OpenLocation_RequiresNewArea = Path.parse("./OpenLocation/requiresNewArea");
		public static final Path _OpenLocation_RequiresNewRegion = Path.parse("./OpenLocation/requiresNewRegion");
		public static final Path _OpenLocation_AcceptsReturns = Path.parse("./OpenLocation/acceptsReturns");
		public static final Path _OpenLocation_DoesRentals = Path.parse("./OpenLocation/doesRentals");
		public static final Path _OpenLocation_Fees = Path.parse("./OpenLocation/Fees");
		public static final Path _OpenLocation_Fees_PrimaryCurrency = Path.parse("./OpenLocation/Fees/primaryCurrency");
		public static final Path _OpenLocation_Fees_RefuelingPurchaseOptionAmount = Path.parse("./OpenLocation/Fees/refuelingPurchaseOptionAmount");
		public static final Path _OpenLocation_Fees_AcSurchargeFee = Path.parse("./OpenLocation/Fees/acSurchargeFee");
		public static final Path _CloseLocation = Path.parse("./CloseLocation");
		public static final Path _CloseLocation_ActualCloseDate = Path.parse("./CloseLocation/actualCloseDate");
		public static final Path _CloseLocation_ProjectedCloseDate = Path.parse("./CloseLocation/projectedCloseDate");
		public static final Path _CloseLocation_LeaseTerminationDate = Path.parse("./CloseLocation/leaseTerminationDate");
		public static final Path _CloseLocation_IsGoingDark = Path.parse("./CloseLocation/isGoingDark");
		public static final Path _CloseLocation_ClosestRentalLocation = Path.parse("./CloseLocation/closestRentalLocation");
		public static final Path _CloseLocation_LeaseTermsAndConditions = Path.parse("./CloseLocation/leaseTermsAndConditions");
		public static final Path _CloseLocation_IsFacilitiesInvolvedInRestoration = Path.parse("./CloseLocation/isFacilitiesInvolvedInRestoration");
		public static final Path _CloseLocation_DoesLocationHaveCopiersPrinters = Path.parse("./CloseLocation/doesLocationHaveCopiersPrinters");
		public static final Path _CloseLocation_ReasonForClosing = Path.parse("./CloseLocation/reasonForClosing");
		public static final Path _CloseLocation_ResDumpDocument = Path.parse("./CloseLocation/ResDumpDocument");
		public static final Path _CloseLocation_ResDumpDocument_Attachment = Path.parse("./CloseLocation/ResDumpDocument/attachment");
		public static final Path _CloseLocation_IT = Path.parse("./CloseLocation/IT");
		public static final Path _CloseLocation_IT_HasEquipmentToBeReturned = Path.parse("./CloseLocation/IT/hasEquipmentToBeReturned");
		public static final Path _CloseLocation_IT_DataLineAction = Path.parse("./CloseLocation/IT/dataLineAction");
		public static final Path _CloseLocation_IT_PhoneLineAction = Path.parse("./CloseLocation/IT/phoneLineAction");
		public static final Path _CloseLocation_IT_HasPrintersCopiersToBePickedUp = Path.parse("./CloseLocation/IT/hasPrintersCopiersToBePickedUp");
		public static final Path _CloseLocation_IT_RelocationOfEquipment = Path.parse("./CloseLocation/IT/relocationOfEquipment");
		public static final Path _CloseLocation_Checklists = Path.parse("./CloseLocation/Checklists");
		public static final Path _CloseLocation_Checklists_PreCloseChecklist = Path.parse("./CloseLocation/Checklists/PreCloseChecklist");
		public static final Path _CloseLocation_Checklists_PreCloseChecklist_IsSignageRemoved = Path.parse("./CloseLocation/Checklists/PreCloseChecklist/isSignageRemoved");
		public static final Path _CloseLocation_Checklists_PreCloseChecklist_AreOpenRentalAgreementsHandled = Path.parse("./CloseLocation/Checklists/PreCloseChecklist/areOpenRentalAgreementsHandled");
		public static final Path _CloseLocation_Checklists_PreCloseChecklist_HasInventoryOfHertzPropertyBeenHandled = Path.parse("./CloseLocation/Checklists/PreCloseChecklist/hasInventoryOfHertzPropertyBeenHandled");
		public static final Path _CloseLocation_Checklists_PreCloseChecklist_HasAlarmSystemCancelRequestBeenMade = Path.parse("./CloseLocation/Checklists/PreCloseChecklist/hasAlarmSystemCancelRequestBeenMade");
		public static final Path _CloseLocation_Checklists_PreCloseChecklist_HasLeaseBeenTerminated = Path.parse("./CloseLocation/Checklists/PreCloseChecklist/hasLeaseBeenTerminated");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist = Path.parse("./CloseLocation/Checklists/PostCloseChecklist");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HasRentalCounterBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/hasRentalCounterBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HasFunitureBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/hasFunitureBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveNotifiedTreasuryOfClosingDepositoryAccount = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveNotifiedTreasuryOfClosingDepositoryAccount");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveCompletedFormsAndDocuments = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveCompletedFormsAndDocuments");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveHandledDispositionOfEmployees = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveHandledDispositionOfEmployees");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_RequestedCancellationOfFuelWashCards = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/requestedCancellationOfFuelWashCards");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_RequestedCancellationOfGenericEmailAddress = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/requestedCancellationOfGenericEmailAddress");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HasManagerFundBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/hasManagerFundBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HavePettyCashChecksBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/havePettyCashChecksBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveBadgesBeenCollectedAndDestroyed = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveBadgesBeenCollectedAndDestroyed");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HasPurchasingCardBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/hasPurchasingCardBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveRepeatingPOsBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveRepeatingPOsBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveDrawdownPOsBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveDrawdownPOsBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HasShreddingServicesBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/hasShreddingServicesBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveRadiosAndCellPhonesBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveRadiosAndCellPhonesBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveTemporarySignageMapBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveTemporarySignageMapBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveWorksCompIssuesBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveWorksCompIssuesBeenHandled");
		public static final Path _CloseLocation_Checklists_PostCloseChecklist_HaveManualRentalAgreementsBeenHandled = Path.parse("./CloseLocation/Checklists/PostCloseChecklist/haveManualRentalAgreementsBeenHandled");
		public static final Path _CloseLocation_DependentChildLocations = Path.parse("./CloseLocation/dependentChildLocations");
		public static final Path _MoveLocation = Path.parse("./MoveLocation");
		public static final Path _MoveLocation_ExistingLocation = Path.parse("./MoveLocation/ExistingLocation");
		public static final Path _MoveLocation_ExistingLocation_ActualCloseDate = Path.parse("./MoveLocation/ExistingLocation/actualCloseDate");
		public static final Path _MoveLocation_ExistingLocation_ProjectedCloseDate = Path.parse("./MoveLocation/ExistingLocation/projectedCloseDate");
		public static final Path _MoveLocation_ExistingLocation_IsFacilitiesInvolvedInRestoration = Path.parse("./MoveLocation/ExistingLocation/isFacilitiesInvolvedInRestoration");
		public static final Path _MoveLocation_ExistingLocation_IsTempCloseRequired = Path.parse("./MoveLocation/ExistingLocation/isTempCloseRequired");
		public static final Path _MoveLocation_ExistingLocation_DoesLocationHaveCopiersPrinters = Path.parse("./MoveLocation/ExistingLocation/doesLocationHaveCopiersPrinters");
		public static final Path _MoveLocation_NewLocation = Path.parse("./MoveLocation/NewLocation");
		public static final Path _MoveLocation_NewLocation_ActualOpenDate = Path.parse("./MoveLocation/NewLocation/actualOpenDate");
		public static final Path _MoveLocation_NewLocation_ProjectedOpenDate = Path.parse("./MoveLocation/NewLocation/projectedOpenDate");
		public static final Path _MoveLocation_NewLocation_LocationMoveToAddress = Path.parse("./MoveLocation/NewLocation/locationMoveToAddress");
		public static final Path _MoveLocation_NewLocation_EnvironmentalAffairs = Path.parse("./MoveLocation/NewLocation/EnvironmentalAffairs");
		public static final Path _MoveLocation_NewLocation_EnvironmentalAffairs_VehiclesWashedOnsite = Path.parse("./MoveLocation/NewLocation/EnvironmentalAffairs/vehiclesWashedOnsite");
		public static final Path _MoveLocation_NewLocation_EnvironmentalAffairs_VehicleOilChangesOnSite = Path.parse("./MoveLocation/NewLocation/EnvironmentalAffairs/vehicleOilChangesOnSite");
		public static final Path _MoveLocation_NewLocation_EnvironmentalAffairs_VehiclesRefueledOnSite = Path.parse("./MoveLocation/NewLocation/EnvironmentalAffairs/vehiclesRefueledOnSite");
		public static final Path _MoveLocation_IT = Path.parse("./MoveLocation/IT");
		public static final Path _MoveLocation_IT_DataLineAction = Path.parse("./MoveLocation/IT/dataLineAction");
		public static final Path _MoveLocation_IT_PhoneLineAction = Path.parse("./MoveLocation/IT/phoneLineAction");
		public static final Path _Construction = Path.parse("./Construction");
		public static final Path _Construction_IsConstructionRequired = Path.parse("./Construction/isConstructionRequired");
		public static final Path _Construction_EstimatedConstructionStartDate = Path.parse("./Construction/estimatedConstructionStartDate");
		public static final Path _Construction_EstimatedPodConstructionFinishedDate = Path.parse("./Construction/estimatedPodConstructionFinishedDate");
		public static final Path _Construction_EstimatedPermanentPowerOnDate = Path.parse("./Construction/estimatedPermanentPowerOnDate");
		public static final Path _Construction_HasDesks = Path.parse("./Construction/hasDesks");
		public static final Path _Construction_IsSiteCoLocated = Path.parse("./Construction/isSiteCoLocated");
		public static final Path _Construction_RequiresPainting = Path.parse("./Construction/requiresPainting");
		public static final Path _Construction_RequiresCarpetInstall = Path.parse("./Construction/requiresCarpetInstall");
		public static final Path _Construction_RequiresTileLaid = Path.parse("./Construction/requiresTileLaid");
		public static final Path _Construction_RequiresOtherConstruction = Path.parse("./Construction/requiresOtherConstruction");
		public static final Path _EnvironmentalAffairs = Path.parse("./EnvironmentalAffairs");
		public static final Path _EnvironmentalAffairs_VehiclesWashedOnsite = Path.parse("./EnvironmentalAffairs/vehiclesWashedOnsite");
		public static final Path _EnvironmentalAffairs_VehicleOilChangesOnSite = Path.parse("./EnvironmentalAffairs/vehicleOilChangesOnSite");
		public static final Path _EnvironmentalAffairs_VehiclesRefueledOnSite = Path.parse("./EnvironmentalAffairs/vehiclesRefueledOnSite");
		public static final Path _LE = Path.parse("./LE");
		public static final Path _LE_UsesLECounterSystem = Path.parse("./LE/usesLECounterSystem");
		public static final Path _LE_OffersLEServices = Path.parse("./LE/offersLEServices");
		public static final Path _LE_OffersPickupServiceCabReimbursement = Path.parse("./LE/offersPickupServiceCabReimbursement");
		public static final Path _LE_OffersInsuranceReplacementRentals = Path.parse("./LE/offersInsuranceReplacementRentals");
		public static final Path _LE_DoesCorporateFreeSell = Path.parse("./LE/doesCorporateFreeSell");
		public static final Path _LE_HonorsPromosCoupons = Path.parse("./LE/honorsPromosCoupons");
		public static final Path _LE__serviceRadius = Path.parse("./LE/_serviceRadius");
		public static final Path _LE__serviceRadiusUOM = Path.parse("./LE/_serviceRadiusUOM");
		public static final Path _InformationTechnology = Path.parse("./InformationTechnology");
		public static final Path _InformationTechnology_NewEquipmentRequired = Path.parse("./InformationTechnology/NewEquipmentRequired");
		public static final Path _InformationTechnology_NewEquipmentRequired_CounterWorkstationCount = Path.parse("./InformationTechnology/NewEquipmentRequired/counterWorkstationCount");
		public static final Path _InformationTechnology_NewEquipmentRequired_BackOfficePCCount = Path.parse("./InformationTechnology/NewEquipmentRequired/backOfficePCCount");
		public static final Path _InformationTechnology_NewEquipmentRequired_MotionTabletCount = Path.parse("./InformationTechnology/NewEquipmentRequired/motionTabletCount");
		public static final Path _InformationTechnology_NewEquipmentRequired_MotionTabletPrinterCount = Path.parse("./InformationTechnology/NewEquipmentRequired/motionTabletPrinterCount");
		public static final Path _InformationTechnology_NewEquipmentRequired_PrinterScannerCount = Path.parse("./InformationTechnology/NewEquipmentRequired/printerScannerCount");
		public static final Path _InformationTechnology_NewEquipmentRequired_InformationMonitorsVideoWallCount = Path.parse("./InformationTechnology/NewEquipmentRequired/informationMonitorsVideoWallCount");
		public static final Path _InformationTechnology_NewEquipmentRequired_ExpressRentKioskCount = Path.parse("./InformationTechnology/NewEquipmentRequired/expressRentKioskCount");
		public static final Path _InformationTechnology_NewEquipmentRequired_ComboPCCount = Path.parse("./InformationTechnology/NewEquipmentRequired/comboPCCount");
		public static final Path _InformationTechnology_ReuseOfExistingEquipment = Path.parse("./InformationTechnology/ReuseOfExistingEquipment");
		public static final Path _InformationTechnology_ReuseOfExistingEquipment_ResuedSignatureCapturePadCount = Path.parse("./InformationTechnology/ReuseOfExistingEquipment/resuedSignatureCapturePadCount");
		public static final Path _InformationTechnology_ReuseOfExistingEquipment_ReusedWhiteASAPCardReaderCount = Path.parse("./InformationTechnology/ReuseOfExistingEquipment/reusedWhiteASAPCardReaderCount");
		public static final Path _InformationTechnology_ReuseOfExistingEquipment_ReusedBlackHLECardReaderCount = Path.parse("./InformationTechnology/ReuseOfExistingEquipment/reusedBlackHLECardReaderCount");
		public static final Path _InformationTechnology_ReuseOfExistingEquipment_OfficeEquipmentInventories = Path.parse("./InformationTechnology/ReuseOfExistingEquipment/officeEquipmentInventories");
		public static final Path _InformationTechnology_NetworkPhones = Path.parse("./InformationTechnology/NetworkPhones");
		public static final Path _InformationTechnology_NetworkPhones_BusinessAllowsUseOfNetwork = Path.parse("./InformationTechnology/NetworkPhones/businessAllowsUseOfNetwork");
		public static final Path _InformationTechnology_NetworkPhones_VoiceLineCount = Path.parse("./InformationTechnology/NetworkPhones/voiceLineCount");
		public static final Path _InformationTechnology_NetworkPhones_CordedPhoneCount = Path.parse("./InformationTechnology/NetworkPhones/cordedPhoneCount");
		public static final Path _InformationTechnology_NetworkPhones_CordlessPhoneCount = Path.parse("./InformationTechnology/NetworkPhones/cordlessPhoneCount");
		public static final Path _InformationTechnology_NetworkPhones_IsVoicemailRequired = Path.parse("./InformationTechnology/NetworkPhones/isVoicemailRequired");
		public static final Path _InformationTechnology_NetworkPhones_IsAutomatedAttendantRequired = Path.parse("./InformationTechnology/NetworkPhones/isAutomatedAttendantRequired");
		public static final Path _InformationTechnology_NetworkPhones_IsDialerPhoneRequired = Path.parse("./InformationTechnology/NetworkPhones/isDialerPhoneRequired");
		public static final Path _InformationTechnology_NetworkPhones_IsNewDataLineRequired = Path.parse("./InformationTechnology/NetworkPhones/isNewDataLineRequired");
		public static final Path _InformationTechnology_AdditionalNetworking = Path.parse("./InformationTechnology/additionalNetworking");
		public static final Path _InformationTechnology_AdditionalNetworking_AdditionalDataDropCount = Path.parse("./InformationTechnology/additionalNetworking/additionalDataDropCount");
		public static final Path _InformationTechnology_AdditionalNetworking_ConferenceRoomCount = Path.parse("./InformationTechnology/additionalNetworking/conferenceRoomCount");
		public static final Path _InformationTechnology_AdditionalNetworking_FaxLineCount = Path.parse("./InformationTechnology/additionalNetworking/faxLineCount");
		public static final Path _InformationTechnology_AdditionalNetworking_TabletUsageArea = Path.parse("./InformationTechnology/additionalNetworking/tabletUsageArea");
		public static final Path _InformationTechnology_AdditionalNetworking_TabletUsageAreaUom = Path.parse("./InformationTechnology/additionalNetworking/tabletUsageAreaUom");
		public static final Path _InformationTechnology_AdditionalNetworking_DoesSiteRequireWiTech = Path.parse("./InformationTechnology/additionalNetworking/doesSiteRequireWiTech");
		public static final Path _InformationTechnology_AdditionalNetworking_PhoneLinesRequiredForAlarmFire = Path.parse("./InformationTechnology/additionalNetworking/phoneLinesRequiredForAlarmFire");
		public static final Path _Rate = Path.parse("./Rate");
		public static final Path _Rate_DefaultTemplate = Path.parse("./Rate/defaultTemplate");
		public static final Path _Rate_RatesFrom = Path.parse("./Rate/ratesFrom");
		public static final Path _Tax = Path.parse("./Tax");
		public static final Path _Tax_PrimaryCurrency = Path.parse("./Tax/primaryCurrency");
		public static final Path _Tax_IsLegalEntity = Path.parse("./Tax/isLegalEntity");
		public static final Path _Tax_HasTaxRegistrationBeenObtained = Path.parse("./Tax/hasTaxRegistrationBeenObtained");
		public static final Path _Tax_HasBusinessLicenseBeenAppliedFor = Path.parse("./Tax/hasBusinessLicenseBeenAppliedFor");
		public static final Path _Tax_TransactionFee = Path.parse("./Tax/transactionFee");
		public static final Path _Tax_VehicleLicenseFee = Path.parse("./Tax/vehicleLicenseFee");
		public static final Path _Tax_RentalAgreementTaxRateAssessed = Path.parse("./Tax/rentalAgreementTaxRateAssessed");
		public static final Path _Tax_TaxRateChange = Path.parse("./Tax/TaxRateChange");
		public static final Path _Tax_TaxRateChange_CaliforniaLocalFuelRate = Path.parse("./Tax/TaxRateChange/californiaLocalFuelRate");
		public static final Path _Tax_TaxRateChange_MotorVehicleRentalTaxRate = Path.parse("./Tax/TaxRateChange/motorVehicleRentalTaxRate");
		public static final Path _Tax_TaxRateChange_MotorVehicleSurcharge = Path.parse("./Tax/TaxRateChange/motorVehicleSurcharge");
		public static final Path _Tax_TaxRateChange_MotorVehicleSurchargePercent = Path.parse("./Tax/TaxRateChange/motorVehicleSurchargePercent");
		public static final Path _Tax_TaxRateChange_MotorVehicleRecovery = Path.parse("./Tax/TaxRateChange/motorVehicleRecovery");
		public static final Path _Tax_TaxRateChange_MotorVehicleRecoveryPercent = Path.parse("./Tax/TaxRateChange/motorVehicleRecoveryPercent");
		public static final Path _ProjectStartEndDates = Path.parse("./ProjectStartEndDates");
		public static final Path _ProjectStartEndDates_StartDate = Path.parse("./ProjectStartEndDates/startDate");
		public static final Path _ProjectStartEndDates_EndDate = Path.parse("./ProjectStartEndDates/endDate");
		public static final Path _ProjectTeamMembers = Path.parse("./projectTeamMembers");
		public static final Path _Domain = Path.parse("./domain");
		public static final Path _ProjectApprovalRoles = Path.parse("./projectApprovalRoles");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	public static final Path _Root_ProjectData = _Root.add("ProjectData");

	// Table type path
	public final class _Root_ProjectData_Address
	{
		private static final Path _Root_ProjectData_Address = _Root_ProjectData.add("Address");
		public static Path getPathInSchema()
		{
			return _Root_ProjectData_Address;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _LocationProject = Path.parse("./locationProject");
		public static final Path _Type = Path.parse("./type");
		public static final Path _PrimarySecondary = Path.parse("./primarySecondary");
		public static final Path _Region = Path.parse("./region");
		public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
		public static final Path _Address = Path.parse("./Address");
		public static final Path _Address_StreetNumber = Path.parse("./Address/streetNumber");
		public static final Path _Address_AddressLine1 = Path.parse("./Address/addressLine1");
		public static final Path _Address_AddressLine2 = Path.parse("./Address/addressLine2");
		public static final Path _Address_AddressLine3 = Path.parse("./Address/addressLine3");
		public static final Path _Address_AddressLine4 = Path.parse("./Address/addressLine4");
		public static final Path _Address_Country = Path.parse("./Address/country");
		public static final Path _Address_StateProvince = Path.parse("./Address/stateProvince");
		public static final Path _Address_County = Path.parse("./Address/county");
		public static final Path _Address_City = Path.parse("./Address/city");
		public static final Path _Address_CityAlternateNames = Path.parse("./Address/cityAlternateNames");
		public static final Path _Address_CityVariants = Path.parse("./Address/cityVariants");
		public static final Path _Address_PostalCode = Path.parse("./Address/postalCode");
		public static final Path _Address_Attention = Path.parse("./Address/attention");
		public static final Path _Address_AdditionalInformation = Path.parse("./Address/additionalInformation");
		public static final Path _Address_Status = Path.parse("./Address/status");
		public static final Path _GeographicPoint = Path.parse("./GeographicPoint");
		public static final Path _GeographicPoint_Latitude = Path.parse("./GeographicPoint/latitude");
		public static final Path _GeographicPoint_Longitude = Path.parse("./GeographicPoint/longitude");
	} 

	// Table type path
	public final class _Root_ProjectData_OfficeEquipmentInventory
	{
		private static final Path _Root_ProjectData_OfficeEquipmentInventory = _Root_ProjectData.add("OfficeEquipmentInventory");
		public static Path getPathInSchema()
		{
			return _Root_ProjectData_OfficeEquipmentInventory;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Project = Path.parse("./project");
		public static final Path _OfficeEquipmentType = Path.parse("./officeEquipmentType");
		public static final Path _Make = Path.parse("./make");
		public static final Path _Model = Path.parse("./model");
		public static final Path _Count = Path.parse("./count");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_ProjectData_LocationProjectTeamMember
	{
		private static final Path _Root_ProjectData_LocationProjectTeamMember = _Root_ProjectData.add("LocationProjectTeamMember");
		public static Path getPathInSchema()
		{
			return _Root_ProjectData_LocationProjectTeamMember;
		}
		public static final Path _Project = Path.parse("./project");
		public static final Path _ProjectRole = Path.parse("./ProjectRole");
		public static final Path __projectRoleName = Path.parse("./_projectRoleName");
		public static final Path _User = Path.parse("./user");
		public static final Path __userid = Path.parse("./_userid");
	} 

	// Table type path
	public final class _Root_ProjectData_ProjectUserTaskLog
	{
		private static final Path _Root_ProjectData_ProjectUserTaskLog = _Root_ProjectData.add("ProjectUserTaskLog");
		public static Path getPathInSchema()
		{
			return _Root_ProjectData_ProjectUserTaskLog;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _ProjectType = Path.parse("./projectType");
		public static final Path _ProjectName = Path.parse("./projectName");
		public static final Path _DataSpace = Path.parse("./dataSpace");
		public static final Path _UserTaskName = Path.parse("./userTaskName");
		public static final Path _OfferedToRole = Path.parse("./offeredToRole");
		public static final Path _AllocatedUser = Path.parse("./allocatedUser");
		public static final Path _TaskStartEndTimestamp = Path.parse("./taskStartEndTimestamp");
		public static final Path _TaskStartEndTimestamp_StartDateTime = Path.parse("./taskStartEndTimestamp/startDateTime");
		public static final Path _TaskStartEndTimestamp_EndDateTime = Path.parse("./taskStartEndTimestamp/endDateTime");
		public static final Path _LastEmailSent = Path.parse("./lastEmailSent");
		public static final Path _IsUserTaskOverdue = Path.parse("./isUserTaskOverdue");
		public static final Path _IsUserTaskActive = Path.parse("./isUserTaskActive");
	} 

	// Table type path
	public final class _Root_Location
	{
		private static final Path _Root_Location = _Root.add("Location");
		public static Path getPathInSchema()
		{
			return _Root_Location;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _IntelligentLocationId = Path.parse("./intelligentLocationId");
		public static final Path _LocationNumber = Path.parse("./locationNumber");
		public static final Path _LocationCode = Path.parse("./locationCode");
		public static final Path _Name = Path.parse("./name");
		public static final Path _Address = Path.parse("./address");
		public static final Path _Description = Path.parse("./description");
		public static final Path _OpenCloseDate = Path.parse("./openCloseDate");
		public static final Path _OpenCloseDate_StartDate = Path.parse("./openCloseDate/startDate");
		public static final Path _OpenCloseDate_EndDate = Path.parse("./openCloseDate/endDate");
		public static final Path _Status = Path.parse("./status");
		public static final Path _RentalCarBrand = Path.parse("./rentalCarBrand");
		public static final Path _OperationsOwnershipType = Path.parse("./operationsOwnershipType");
		public static final Path _AlphaCode = Path.parse("./alphaCode");
		public static final Path _IsOnAirportComputed = Path.parse("./isOnAirportComputed");
		public static final Path _IsAirportOperationsComputed = Path.parse("./isAirportOperationsComputed");
		public static final Path _IsMajorAirport = Path.parse("./isMajorAirport");
		public static final Path _IsOnRailComputed = Path.parse("./isOnRailComputed");
		public static final Path _IsBusLocation = Path.parse("./isBusLocation");
		public static final Path _IsCruiseLocation = Path.parse("./isCruiseLocation");
		public static final Path _IsKioskLocation = Path.parse("./isKioskLocation");
		public static final Path _IsHLE = Path.parse("./isHLE");
		public static final Path _IsFleetLocation = Path.parse("./isFleetLocation");
		public static final Path _IsCarSalesLocation = Path.parse("./isCarSalesLocation");
		public static final Path _IsLeasingLocation = Path.parse("./isLeasingLocation");
		public static final Path _IsMilitaryLocation = Path.parse("./isMilitaryLocation");
		public static final Path _IsServedByComputed = Path.parse("./isServedByComputed");
		public static final Path _IsSatellite = Path.parse("./isSatellite");
		public static final Path _IsStaffed = Path.parse("./isStaffed");
		public static final Path _IsStaffedByHertzPersonnel = Path.parse("./isStaffedByHertzPersonnel");
		public static final Path _IsAutomated = Path.parse("./isAutomated");
		public static final Path _IsInPlant = Path.parse("./isInPlant");
		public static final Path _IsDropShip = Path.parse("./isDropShip");
		public static final Path _IsUsedForReservationCenter = Path.parse("./isUsedForReservationCenter");
		public static final Path _ServiceRadius = Path.parse("./serviceRadius");
		public static final Path _ServiceRadiusUom = Path.parse("./serviceRadiusUom");
		public static final Path _Fees = Path.parse("./Fees");
		public static final Path _Fees_PrimaryCurrency = Path.parse("./Fees/primaryCurrency");
		public static final Path _Fees_RefuelingFee = Path.parse("./Fees/refuelingFee");
		public static final Path _LocationInformation = Path.parse("./LocationInformation");
		public static final Path _LocationInformation__locationCountry = Path.parse("./LocationInformation/_locationCountry");
		public static final Path _LocationInformation__locationStateProvince = Path.parse("./LocationInformation/_locationStateProvince");
		public static final Path _LocationInformation_Language = Path.parse("./LocationInformation/language");
		public static final Path _LocationInformation_MeasurementSystem = Path.parse("./LocationInformation/measurementSystem");
		public static final Path _LocationInformation_CountryTimeZone = Path.parse("./LocationInformation/countryTimeZone");
		public static final Path _LocationInformation_StateProvinceTimeZone = Path.parse("./LocationInformation/stateProvinceTimeZone");
		public static final Path _LocationInformation_PrimaryCurrency = Path.parse("./LocationInformation/primaryCurrency");
		public static final Path _LocationInformation_CountryMinimumAge = Path.parse("./LocationInformation/countryMinimumAge");
		public static final Path _LocationInformation_CountryMaximumAge = Path.parse("./LocationInformation/countryMaximumAge");
		public static final Path _LocationInformation_LocationMinimumAge = Path.parse("./LocationInformation/locationMinimumAge");
		public static final Path _LocationInformation_LocationMaximumAge = Path.parse("./LocationInformation/locationMaximumAge");
		public static final Path _LocationInformation_Oag = Path.parse("./LocationInformation/oag");
		public static final Path _LocationInformation_ExtendedOAG = Path.parse("./LocationInformation/extendedOAG");
		public static final Path _LocationInformation_LocationCity = Path.parse("./LocationInformation/locationCity");
		public static final Path _LocationInformation_Region = Path.parse("./LocationInformation/region");
		public static final Path _LocationInformation_AreaBanding = Path.parse("./LocationInformation/AreaBanding");
		public static final Path _LocationInformation_AreaBanding_AreaBanding = Path.parse("./LocationInformation/AreaBanding/areaBanding");
		public static final Path _LocationInformation_AreaBanding_BandingLowerEnd = Path.parse("./LocationInformation/AreaBanding/bandingLowerEnd");
		public static final Path _LocationInformation_AreaBanding_BandingUpperEnd = Path.parse("./LocationInformation/AreaBanding/bandingUpperEnd");
		public static final Path _LocationInformation_Area = Path.parse("./LocationInformation/area");
		public static final Path _LocationInformation_CmsArea = Path.parse("./LocationInformation/cmsArea");
		public static final Path _LocationInformation_FleetArea = Path.parse("./LocationInformation/fleetArea");
		public static final Path _LocationInformation_ReservationArea = Path.parse("./LocationInformation/reservationArea");
		public static final Path _LocationInformation_LocationHierarchies = Path.parse("./LocationInformation/locationHierarchies");
		public static final Path _LocationInformation_SourceSystem = Path.parse("./LocationInformation/SourceSystem");
		public static final Path _LocationInformation_SourceSystem_SourceSystemName = Path.parse("./LocationInformation/SourceSystem/sourceSystemName");
		public static final Path _LocationInformation_SourceSystem_SourceSystemRecordId = Path.parse("./LocationInformation/SourceSystem/sourceSystemRecordId");
		public static final Path _LocationInformation_LocationProjects = Path.parse("./LocationInformation/LocationProjects");
		public static final Path _LocationInformation_LocationProjects_LocationProjects = Path.parse("./LocationInformation/LocationProjects/locationProjects");
		public static final Path _ContactInformation = Path.parse("./ContactInformation");
		public static final Path _ContactInformation_Addresses = Path.parse("./ContactInformation/addresses");
		public static final Path _ContactInformation_Phones = Path.parse("./ContactInformation/phones");
		public static final Path _ContactInformation_EMailAddresses = Path.parse("./ContactInformation/eMailAddresses");
		public static final Path _ContactInformation_Contacts = Path.parse("./ContactInformation/contacts");
		public static final Path _LocationTypes = Path.parse("./LocationTypes");
		public static final Path _LocationTypes_LocationTypes = Path.parse("./LocationTypes/locationTypes");
		public static final Path _LocationTypes_IntelligentLocationIds = Path.parse("./LocationTypes/intelligentLocationIds");
		public static final Path _LocationRelationships = Path.parse("./LocationRelationships");
		public static final Path _LocationRelationships_LocationParentRelationships = Path.parse("./LocationRelationships/locationParentRelationships");
		public static final Path _LocationRelationships_LocationSubRelationships = Path.parse("./LocationRelationships/locationSubRelationships");
		public static final Path _VehicleInformation = Path.parse("./VehicleInformation");
		public static final Path _VehicleInformation_AfterHoursReservations = Path.parse("./VehicleInformation/AfterHoursReservations");
		public static final Path _VehicleInformation_AfterHoursReservations_AfterHoursReservation = Path.parse("./VehicleInformation/AfterHoursReservations/afterHoursReservation");
		public static final Path _VehicleInformation_AfterHoursReturns = Path.parse("./VehicleInformation/AfterHoursReturns");
		public static final Path _VehicleInformation_AfterHoursReturns_WhereShoudCustomerParkVehicle = Path.parse("./VehicleInformation/AfterHoursReturns/whereShoudCustomerParkVehicle");
		public static final Path _VehicleInformation_AfterHoursReturns_WhereisDropBoxLocated = Path.parse("./VehicleInformation/AfterHoursReturns/whereisDropBoxLocated");
		public static final Path _VehicleInformation_AfterHoursReturns_DropOffInstructions = Path.parse("./VehicleInformation/AfterHoursReturns/dropOffInstructions");
		public static final Path _VehicleInformation_CarClasses = Path.parse("./VehicleInformation/carClasses");
		public static final Path _VehicleInformation_Sipp = Path.parse("./VehicleInformation/sipp");
		public static final Path _VehicleInformation_CancellationHoursAndFees = Path.parse("./VehicleInformation/cancellationHoursAndFees");
		public static final Path _ProductsAndServices = Path.parse("./ProductsAndServices");
		public static final Path _ProductsAndServices_PrimaryCurrency = Path.parse("./ProductsAndServices/primaryCurrency");
		public static final Path _ProductsAndServices_AdvancedReservationDate = Path.parse("./ProductsAndServices/advancedReservationDate");
		public static final Path _ProductsAndServices_SsensEMail = Path.parse("./ProductsAndServices/ssensEMail");
		public static final Path _ProductsAndServices_MaximumReimbursementForCab = Path.parse("./ProductsAndServices/maximumReimbursementForCab");
		public static final Path _ProductsAndServices_IsBookableOnline = Path.parse("./ProductsAndServices/isBookableOnline");
		public static final Path _ProductsAndServices_IsGoldAnytimeEnabled = Path.parse("./ProductsAndServices/isGoldAnytimeEnabled");
		public static final Path _ProductsAndServices_GoldService = Path.parse("./ProductsAndServices/goldService");
		public static final Path _ProductsAndServices_HasGoldService = Path.parse("./ProductsAndServices/hasGoldService");
		public static final Path _ProductsAndServices_HasGoldCanopy = Path.parse("./ProductsAndServices/hasGoldCanopy");
		public static final Path _ProductsAndServices_ExpressService = Path.parse("./ProductsAndServices/expressService");
		public static final Path _ProductsAndServices_HasPrestigeService = Path.parse("./ProductsAndServices/hasPrestigeService");
		public static final Path _ProductsAndServices_HasMobileGoldBoard = Path.parse("./ProductsAndServices/hasMobileGoldBoard");
		public static final Path _ProductsAndServices_IsCounterBypassEnabled = Path.parse("./ProductsAndServices/isCounterBypassEnabled");
		public static final Path _ProductsAndServices_HasReturnCenter = Path.parse("./ProductsAndServices/hasReturnCenter");
		public static final Path _ProductsAndServices_HasPickupService = Path.parse("./ProductsAndServices/hasPickupService");
		public static final Path _ProductsAndServices_HasDeliveryService = Path.parse("./ProductsAndServices/hasDeliveryService");
		public static final Path _ProductsAndServices_HasAfterHoursPickup = Path.parse("./ProductsAndServices/hasAfterHoursPickup");
		public static final Path _ProductsAndServices_HasAfterHoursDrop = Path.parse("./ProductsAndServices/hasAfterHoursDrop");
		public static final Path _ProductsAndServices_HasRoadsideAssistance = Path.parse("./ProductsAndServices/hasRoadsideAssistance");
		public static final Path _ProductsAndServices_CanRefuel = Path.parse("./ProductsAndServices/canRefuel");
		public static final Path _ProductsAndServices_AllowTruckVanRental = Path.parse("./ProductsAndServices/allowTruckVanRental");
		public static final Path _ProductsAndServices_AllowHeavyTruckRental = Path.parse("./ProductsAndServices/allowHeavyTruckRental");
		public static final Path _ProductsAndServices_IsPreRent72Hours = Path.parse("./ProductsAndServices/isPreRent72Hours");
		public static final Path _ProductsAndServices_IsLocation247 = Path.parse("./ProductsAndServices/isLocation247");
		public static final Path _ProductsAndServices_OffersRentalAndInsuranceReplacement = Path.parse("./ProductsAndServices/offersRentalAndInsuranceReplacement");
		public static final Path _ProductsAndServices_HasInsuranceReplacementOnly = Path.parse("./ProductsAndServices/hasInsuranceReplacementOnly");
		public static final Path _ProductsAndServices_HertzOnDemandImage = Path.parse("./ProductsAndServices/hertzOnDemandImage");
		public static final Path _ProductsAndServices_ReferToQualificationsAndRequirements = Path.parse("./ProductsAndServices/referToQualificationsAndRequirements");
		public static final Path _ProductsAndServices_IsVRACVehicleUpgrade = Path.parse("./ProductsAndServices/isVRACVehicleUpgrade");
		public static final Path _ProductsAndServices_IsChaffeurLocation = Path.parse("./ProductsAndServices/isChaffeurLocation");
		public static final Path _ProductsAndServices_HasWIFI = Path.parse("./ProductsAndServices/hasWIFI");
		public static final Path _ProductsAndServices_HasNeverLost = Path.parse("./ProductsAndServices/hasNeverLost");
		public static final Path _ProductsAndServices_HasTollProduct = Path.parse("./ProductsAndServices/hasTollProduct");
		public static final Path _ProductsAndServices_HasLuggageRacks = Path.parse("./ProductsAndServices/hasLuggageRacks");
		public static final Path _ProductsAndServices_HasChildSeats = Path.parse("./ProductsAndServices/hasChildSeats");
		public static final Path _ProductsAndServices_HasBoosterSeats = Path.parse("./ProductsAndServices/hasBoosterSeats");
		public static final Path _ProductsAndServices_HasInfantSeats = Path.parse("./ProductsAndServices/hasInfantSeats");
		public static final Path _ProductsAndServices_HasHandControl = Path.parse("./ProductsAndServices/hasHandControl");
		public static final Path _ProductsAndServices_IsSkierized = Path.parse("./ProductsAndServices/isSkierized");
		public static final Path _ProductsAndServices_Yield = Path.parse("./ProductsAndServices/Yield");
		public static final Path _ProductsAndServices_Yield_VawPool = Path.parse("./ProductsAndServices/Yield/vawPool");
		public static final Path _ProductsAndServices_Yield_FleetFrom = Path.parse("./ProductsAndServices/Yield/fleetFrom");
		public static final Path _ProductsAndServices_ContributionManagementSystem = Path.parse("./ProductsAndServices/ContributionManagementSystem");
		public static final Path _ProductsAndServices_ContributionManagementSystem_CmsPool = Path.parse("./ProductsAndServices/ContributionManagementSystem/cmsPool");
		public static final Path _ProductsAndServices_ContributionManagementSystem_CmsLocationGroup = Path.parse("./ProductsAndServices/ContributionManagementSystem/cmsLocationGroup");
		public static final Path _ProductsAndServices_AirportLocations = Path.parse("./ProductsAndServices/AirportLocations");
		public static final Path _ProductsAndServices_AirportLocations_IsFixedBasedOperatorFBO = Path.parse("./ProductsAndServices/AirportLocations/isFixedBasedOperatorFBO");
		public static final Path _ProductsAndServices_AirportLocations_AreWalkInsPermitted = Path.parse("./ProductsAndServices/AirportLocations/areWalkInsPermitted");
		public static final Path _ProductsAndServices_AirportLocations_IsFlightMandatoryAll = Path.parse("./ProductsAndServices/AirportLocations/isFlightMandatoryAll");
		public static final Path _ProductsAndServices_AirportLocations_PrivateFlightsOnly = Path.parse("./ProductsAndServices/AirportLocations/privateFlightsOnly");
		public static final Path _ProductsAndServices_AirportLocations_CanMeetPrivateFlight = Path.parse("./ProductsAndServices/AirportLocations/canMeetPrivateFlight");
		public static final Path _ProductsAndServices_AirportLocations_IsPrivateFlightNumberMandatory = Path.parse("./ProductsAndServices/AirportLocations/isPrivateFlightNumberMandatory");
		public static final Path _ProductsAndServices_Hotels = Path.parse("./ProductsAndServices/Hotels");
		public static final Path _ProductsAndServices_Hotels_HotelGuestsOnly = Path.parse("./ProductsAndServices/Hotels/hotelGuestsOnly");
		public static final Path _ProductsAndServices_Hotels_SpecialInstructions = Path.parse("./ProductsAndServices/Hotels/specialInstructions");
		public static final Path _ProductsAndServices_LocationDistances = Path.parse("./ProductsAndServices/LocationDistances");
		public static final Path _ProductsAndServices_LocationDistances_PrimaryCurrency = Path.parse("./ProductsAndServices/LocationDistances/primaryCurrency");
		public static final Path _ProductsAndServices_LocationDistances_DistanceUOM = Path.parse("./ProductsAndServices/LocationDistances/distanceUOM");
		public static final Path _ProductsAndServices_LocationDistances_DistanceToBusStation = Path.parse("./ProductsAndServices/LocationDistances/distanceToBusStation");
		public static final Path _ProductsAndServices_LocationDistances_BusStationCabFare = Path.parse("./ProductsAndServices/LocationDistances/busStationCabFare");
		public static final Path _ProductsAndServices_LocationDistances_MaximumReimbursementForBusFare = Path.parse("./ProductsAndServices/LocationDistances/maximumReimbursementForBusFare");
		public static final Path _ProductsAndServices_LocationDistances_DistanceToRailroadStation = Path.parse("./ProductsAndServices/LocationDistances/distanceToRailroadStation");
		public static final Path _ProductsAndServices_LocationDistances_RailroadStationCabFare = Path.parse("./ProductsAndServices/LocationDistances/railroadStationCabFare");
		public static final Path _ProductsAndServices_LocationDistances_MaximumReimbursementForRailroad = Path.parse("./ProductsAndServices/LocationDistances/maximumReimbursementForRailroad");
		public static final Path _ProductsAndServices_LocationDistances_DistanceToPier = Path.parse("./ProductsAndServices/LocationDistances/distanceToPier");
		public static final Path _ProductsAndServices_LocationDistances_PierCabFare = Path.parse("./ProductsAndServices/LocationDistances/pierCabFare");
		public static final Path _ProductsAndServices_LocationDistances_MaximumReimbursementForPier = Path.parse("./ProductsAndServices/LocationDistances/maximumReimbursementForPier");
		public static final Path _ProductsAndServices_Directions = Path.parse("./ProductsAndServices/Directions");
		public static final Path _ProductsAndServices_Directions_ClosestCommercialAirport = Path.parse("./ProductsAndServices/Directions/closestCommercialAirport");
		public static final Path _ProductsAndServices_Directions_GeneralDirectionFromAirport = Path.parse("./ProductsAndServices/Directions/generalDirectionFromAirport");
		public static final Path _ServiceHours = Path.parse("./ServiceHours");
		public static final Path _ServiceHours_ServiceHours = Path.parse("./ServiceHours/serviceHours");
		public static final Path _ServiceHours_SeasonalServiceHours = Path.parse("./ServiceHours/seasonalServiceHours");
		public static final Path _Websites = Path.parse("./Websites");
		public static final Path _Websites_CustomerFacingLocationName = Path.parse("./Websites/customerFacingLocationName");
		public static final Path _Websites_CustomerFacingAreaName = Path.parse("./Websites/customerFacingAreaName");
		public static final Path _Websites_CustomerFacingCountryName = Path.parse("./Websites/customerFacingCountryName");
		public static final Path _Websites_DisplayHLEText = Path.parse("./Websites/displayHLEText");
		public static final Path _Websites_EilieoId = Path.parse("./Websites/eilieoId");
		public static final Path _Websites_MeetsAdvancedReservations = Path.parse("./Websites/meetsAdvancedReservations");
		public static final Path _Websites_CustomerFacingAdditionalInformation = Path.parse("./Websites/customerFacingAdditionalInformation");
		public static final Path _Websites_Websites = Path.parse("./Websites/websites");
		public static final Path _Indicators = Path.parse("./indicators");
		public static final Path _Currencies = Path.parse("./currencies");
		public static final Path _Notes = Path.parse("./Notes");
		public static final Path _Notes_LocationNotes = Path.parse("./Notes/locationNotes");
		public static final Path _Notes_Notes = Path.parse("./Notes/notes");
		public static final Path _CurrentProjectType = Path.parse("./currentProjectType");
		public static final Path _ResetIntelligentIds = Path.parse("./resetIntelligentIds");
		public static final Path _ResetReplicatedBooleanValues = Path.parse("./resetReplicatedBooleanValues");
		public static final Path _ResetPrimaryCurrencyCode = Path.parse("./resetPrimaryCurrencyCode");
		public static final Path _IsOnAirport = Path.parse("./isOnAirport");
		public static final Path _IsAirportOperations = Path.parse("./isAirportOperations");
		public static final Path _IsOnRail = Path.parse("./isOnRail");
		public static final Path _IsServedBy = Path.parse("./isServedBy");
		public static final Path _IsSatelliteComputed = Path.parse("./isSatelliteComputed");
		public static final Path _IsStaffedByHertzPersonnelComputed = Path.parse("./isStaffedByHertzPersonnelComputed");
	} 
	public static final Path _Root_LocationData = _Root.add("LocationData");

	// Table type path
	public final class _Root_LocationData_Address
	{
		private static final Path _Root_LocationData_Address = _Root_LocationData.add("Address");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_Address;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Location = Path.parse("./location");
		public static final Path _Type = Path.parse("./type");
		public static final Path _PrimarySecondary = Path.parse("./primarySecondary");
		public static final Path _Address = Path.parse("./Address");
		public static final Path _Address_StreetNumber = Path.parse("./Address/streetNumber");
		public static final Path _Address_AddressLine1 = Path.parse("./Address/addressLine1");
		public static final Path _Address_AddressLine2 = Path.parse("./Address/addressLine2");
		public static final Path _Address_AddressLine3 = Path.parse("./Address/addressLine3");
		public static final Path _Address_AddressLine4 = Path.parse("./Address/addressLine4");
		public static final Path _Address_Country = Path.parse("./Address/country");
		public static final Path _Address_StateProvince = Path.parse("./Address/stateProvince");
		public static final Path _Address_County = Path.parse("./Address/county");
		public static final Path _Address_City = Path.parse("./Address/city");
		public static final Path _Address_CityAlternateNames = Path.parse("./Address/cityAlternateNames");
		public static final Path _Address_CityVariants = Path.parse("./Address/cityVariants");
		public static final Path _Address_PostalCode = Path.parse("./Address/postalCode");
		public static final Path _Address_Attention = Path.parse("./Address/attention");
		public static final Path _Address_AdditionalInformation = Path.parse("./Address/additionalInformation");
		public static final Path _Address_Status = Path.parse("./Address/status");
		public static final Path _GeographicPoint = Path.parse("./GeographicPoint");
		public static final Path _GeographicPoint_Latitude = Path.parse("./GeographicPoint/latitude");
		public static final Path _GeographicPoint_Longitude = Path.parse("./GeographicPoint/longitude");
		public static final Path _Region = Path.parse("./region");
		public static final Path _DropshipCodes = Path.parse("./dropshipCodes");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_Contact
	{
		private static final Path _Root_LocationData_Contact = _Root_LocationData.add("Contact");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_Contact;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Location = Path.parse("./location");
		public static final Path _BusinessParty = Path.parse("./businessParty");
		public static final Path _BusinessPartyType = Path.parse("./businessPartyType");
		public static final Path _ContactType = Path.parse("./contactType");
		public static final Path _PrimarySecondary = Path.parse("./primarySecondary");
		public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_EMailAddress
	{
		private static final Path _Root_LocationData_EMailAddress = _Root_LocationData.add("eMailAddress");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_EMailAddress;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Location = Path.parse("./location");
		public static final Path _EMailAddressType = Path.parse("./eMailAddressType");
		public static final Path _PrimarySecondary = Path.parse("./primarySecondary");
		public static final Path _EMailAddress = Path.parse("./eMailAddress");
		public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_Phone
	{
		private static final Path _Root_LocationData_Phone = _Root_LocationData.add("Phone");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_Phone;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Location = Path.parse("./location");
		public static final Path _PhoneType = Path.parse("./phoneType");
		public static final Path _PrimarySecondary = Path.parse("./primarySecondary");
		public static final Path _PhoneNumber = Path.parse("./PhoneNumber");
		public static final Path _PhoneNumber_CountryCode = Path.parse("./PhoneNumber/countryCode");
		public static final Path _PhoneNumber_AreaCode = Path.parse("./PhoneNumber/areaCode");
		public static final Path _PhoneNumber_LocalNumber = Path.parse("./PhoneNumber/localNumber");
		public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_ServiceDays
	{
		private static final Path _Root_LocationData_ServiceDays = _Root_LocationData.add("ServiceDays");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_ServiceDays;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Location = Path.parse("./location");
		public static final Path __locationName = Path.parse("./_locationName");
		public static final Path _ServiceHoursType = Path.parse("./serviceHoursType");
		public static final Path _IsSeasonal = Path.parse("./isSeasonal");
		public static final Path _DayOfWeek = Path.parse("./dayOfWeek");
		public static final Path _DateRange = Path.parse("./DateRange");
		public static final Path _DateRange_StartDate = Path.parse("./DateRange/startDate");
		public static final Path _DateRange_EndDate = Path.parse("./DateRange/endDate");
		public static final Path _SeasonalDateRange = Path.parse("./SeasonalDateRange");
		public static final Path _SeasonalDateRange_StartMonth = Path.parse("./SeasonalDateRange/startMonth");
		public static final Path _SeasonalDateRange_StartDay = Path.parse("./SeasonalDateRange/startDay");
		public static final Path _SeasonalDateRange_EndMonth = Path.parse("./SeasonalDateRange/endMonth");
		public static final Path _SeasonalDateRange_EndDay = Path.parse("./SeasonalDateRange/endDay");
		public static final Path _IsOpen24Hours = Path.parse("./isOpen24Hours");
		public static final Path _IsClosedOnThisDay = Path.parse("./isClosedOnThisDay");
		public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
		public static final Path _ServiceHoursTimes = Path.parse("./serviceHoursTimes");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_ServiceHours
	{
		private static final Path _Root_LocationData_ServiceHours = _Root_LocationData.add("ServiceHours");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_ServiceHours;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _ServiceDays = Path.parse("./serviceDays");
		public static final Path _TimeRange = Path.parse("./TimeRange");
		public static final Path _TimeRange_StartTime = Path.parse("./TimeRange/startTime");
		public static final Path _TimeRange_EndTime = Path.parse("./TimeRange/endTime");
		public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationNotes
	{
		private static final Path _Root_LocationData_LocationNotes = _Root_LocationData.add("LocationNotes");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationNotes;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _Location = Path.parse("./location");
		public static final Path _NotesType = Path.parse("./notesType");
		public static final Path _CreatedBy = Path.parse("./createdBy");
		public static final Path _CreatedDateTime = Path.parse("./createdDateTime");
		public static final Path _Note = Path.parse("./note");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationUpdateNotification
	{
		private static final Path _Root_LocationData_LocationUpdateNotification = _Root_LocationData.add("LocationUpdateNotification");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationUpdateNotification;
		}
		public static final Path _CreatedDateTime = Path.parse("./createdDateTime");
		public static final Path _Location = Path.parse("./location");
		public static final Path _UpdateType = Path.parse("./updateType");
		public static final Path _TableUpdated = Path.parse("./tableUpdated");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationAncillaryRelationship
	{
		private static final Path _Root_LocationData_LocationAncillaryRelationship = _Root_LocationData.add("LocationAncillaryRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationAncillaryRelationship;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Location = Path.parse("./location");
		public static final Path _Ancillary = Path.parse("./ancillary");
		public static final Path _DailyRate = Path.parse("./dailyRate");
		public static final Path _ReplacementCost = Path.parse("./replacementCost");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationAddressDropShipCodeRelationship
	{
		private static final Path _Root_LocationData_LocationAddressDropShipCodeRelationship = _Root_LocationData.add("LocationAddressDropShipCodeRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationAddressDropShipCodeRelationship;
		}
		public static final Path _Address = Path.parse("./address");
		public static final Path _DropshipCode = Path.parse("./dropshipCode");
		public static final Path _Location = Path.parse("./location");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationCarClassRelationship
	{
		private static final Path _Root_LocationData_LocationCarClassRelationship = _Root_LocationData.add("LocationCarClassRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationCarClassRelationship;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Location = Path.parse("./location");
		public static final Path _CarClass = Path.parse("./carClass");
		public static final Path _Currency = Path.parse("./currency");
		public static final Path __country = Path.parse("./_country");
		public static final Path _PaymentTypes = Path.parse("./paymentTypes");
		public static final Path _LocationCarClassAncillaries = Path.parse("./locationCarClassAncillaries");
		public static final Path _AfterHours = Path.parse("./AfterHours");
		public static final Path _AfterHours_AfterHoursBookingRequiredHours = Path.parse("./AfterHours/afterHoursBookingRequiredHours");
		public static final Path _AfterHours_AfterHoursCancellationRequiredHours = Path.parse("./AfterHours/afterHoursCancellationRequiredHours");
		public static final Path _AfterHours_AfterHoursCancellationFee = Path.parse("./AfterHours/afterHoursCancellationFee");
		public static final Path _VehicleGuarantees = Path.parse("./VehicleGuarantees");
		public static final Path _VehicleGuarantees_AdvancedBookingRequiredHours = Path.parse("./VehicleGuarantees/advancedBookingRequiredHours");
		public static final Path _VehicleGuarantees_AdvancedCancellationRequiredHours = Path.parse("./VehicleGuarantees/advancedCancellationRequiredHours");
		public static final Path _VehicleGuarantees_CancellationFee = Path.parse("./VehicleGuarantees/cancellationFee");
		public static final Path _MinimumAge = Path.parse("./minimumAge");
		public static final Path _MaximumAge = Path.parse("./maximumAge");
		public static final Path _TankSize = Path.parse("./tankSize");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationCarClassPaymentTypeRelationship
	{
		private static final Path _Root_LocationData_LocationCarClassPaymentTypeRelationship = _Root_LocationData.add("LocationCarClassPaymentTypeRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationCarClassPaymentTypeRelationship;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _LocationCarClassRelationship = Path.parse("./locationCarClassRelationship");
		public static final Path _PaymentType = Path.parse("./paymentType");
		public static final Path _PaymentTypeTiming = Path.parse("./paymentTypeTiming");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationCarClassAncillaryRelationship
	{
		private static final Path _Root_LocationData_LocationCarClassAncillaryRelationship = _Root_LocationData.add("LocationCarClassAncillaryRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationCarClassAncillaryRelationship;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _LocationCarClassRelationship = Path.parse("./locationCarClassRelationship");
		public static final Path _Ancillary = Path.parse("./ancillary");
		public static final Path _DailyRate = Path.parse("./dailyRate");
		public static final Path _ReplacementCost = Path.parse("./replacementCost");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationCurrencyRelationship
	{
		private static final Path _Root_LocationData_LocationCurrencyRelationship = _Root_LocationData.add("LocationCurrencyRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationCurrencyRelationship;
		}
		public static final Path _Location = Path.parse("./location");
		public static final Path _Currency = Path.parse("./currency");
		public static final Path _IsPrimaryCurrency = Path.parse("./isPrimaryCurrency");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationIndicatorRelationship
	{
		private static final Path _Root_LocationData_LocationIndicatorRelationship = _Root_LocationData.add("LocationIndicatorRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationIndicatorRelationship;
		}
		public static final Path _Location = Path.parse("./location");
		public static final Path _Indicator = Path.parse("./indicator");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationIntelligentLocationIdRelationship
	{
		private static final Path _Root_LocationData_LocationIntelligentLocationIdRelationship = _Root_LocationData.add("locationIntelligentLocationIdRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationIntelligentLocationIdRelationship;
		}
		public static final Path _Location = Path.parse("./location");
		public static final Path __intelligentLocationId = Path.parse("./_intelligentLocationId");
		public static final Path _LocationName = Path.parse("./locationName");
		public static final Path _LocationNumber = Path.parse("./locationNumber");
		public static final Path _LocationCode = Path.parse("./locationCode");
		public static final Path _IsPrimary = Path.parse("./isPrimary");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationLocationRelationship
	{
		private static final Path _Root_LocationData_LocationLocationRelationship = _Root_LocationData.add("LocationLocationRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationLocationRelationship;
		}
		public static final Path _ParentLocation = Path.parse("./parentLocation");
		public static final Path _SubLocation = Path.parse("./subLocation");
		public static final Path _LocationRelationshipType = Path.parse("./locationRelationshipType");
		public static final Path _Distance = Path.parse("./distance");
		public static final Path _DispositionOfChildWhenParentClosed = Path.parse("./dispositionOfChildWhenParentClosed");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationLocationTypeGroupRelationship
	{
		private static final Path _Root_LocationData_LocationLocationTypeGroupRelationship = _Root_LocationData.add("LocationLocationTypeGroupRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationLocationTypeGroupRelationship;
		}
		public static final Path _Location = Path.parse("./location");
		public static final Path _LocationTypeGroup = Path.parse("./locationTypeGroup");
		public static final Path _LocationType = Path.parse("./locationType");
		public static final Path _LocationTypeGroupParent = Path.parse("./locationTypeGroupParent");
		public static final Path __subFunctionType = Path.parse("./_subFunctionType");
		public static final Path __areMultipleSelectionsAllowed = Path.parse("./_areMultipleSelectionsAllowed");
		public static final Path _LocationTypeGroupType = Path.parse("./locationTypeGroupType");
		public static final Path _LocationTypeGroupTypes = Path.parse("./locationTypeGroupTypes");
		public static final Path _NoMultipleLocationTypeGroup = Path.parse("./noMultipleLocationTypeGroup");
		public static final Path _DisplayLocationTypes = Path.parse("./displayLocationTypes");
		public static final Path _RentalType = Path.parse("./rentalType");
		public static final Path _IsAirportOperations = Path.parse("./isAirportOperations");
		public static final Path __isLeafNode = Path.parse("./_isLeafNode");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationNoteRelationship
	{
		private static final Path _Root_LocationData_LocationNoteRelationship = _Root_LocationData.add("LocationNoteRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationNoteRelationship;
		}
		public static final Path _Location = Path.parse("./location");
		public static final Path _Note = Path.parse("./note");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationPaymentTypeRelationship
	{
		private static final Path _Root_LocationData_LocationPaymentTypeRelationship = _Root_LocationData.add("LocationPaymentTypeRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationPaymentTypeRelationship;
		}
		public static final Path _Location = Path.parse("./location");
		public static final Path _PaymentType = Path.parse("./paymentType");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationSIPPRelationship
	{
		private static final Path _Root_LocationData_LocationSIPPRelationship = _Root_LocationData.add("LocationSIPPRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationSIPPRelationship;
		}
		public static final Path _Location = Path.parse("./location");
		public static final Path _Sipp = Path.parse("./sipp");
		public static final Path _Currency = Path.parse("./currency");
		public static final Path _AfterHours = Path.parse("./AfterHours");
		public static final Path _AfterHours_AfterHoursBookingRequiredHours = Path.parse("./AfterHours/afterHoursBookingRequiredHours");
		public static final Path _AfterHours_AfterHoursCancellationRequiredHours = Path.parse("./AfterHours/afterHoursCancellationRequiredHours");
		public static final Path _AfterHours_AfterHoursCancellationFee = Path.parse("./AfterHours/afterHoursCancellationFee");
		public static final Path _VehicleGuarantees = Path.parse("./VehicleGuarantees");
		public static final Path _VehicleGuarantees_AdvancedBookingRequiredHours = Path.parse("./VehicleGuarantees/advancedBookingRequiredHours");
		public static final Path _VehicleGuarantees_AdvancedCancellationRequiredHours = Path.parse("./VehicleGuarantees/advancedCancellationRequiredHours");
		public static final Path _VehicleGuarantees_CancellationFee = Path.parse("./VehicleGuarantees/cancellationFee");
		public static final Path _MinimumAge = Path.parse("./minimumAge");
		public static final Path _MaximumAge = Path.parse("./maximumAge");
		public static final Path _TankSize = Path.parse("./tankSize");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationData_LocationWebsiteRelationship
	{
		private static final Path _Root_LocationData_LocationWebsiteRelationship = _Root_LocationData.add("LocationWebsiteRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationData_LocationWebsiteRelationship;
		}
		public static final Path _Location = Path.parse("./location");
		public static final Path _Website = Path.parse("./website");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Area
	{
		private static final Path _Root_Area = _Root.add("Area");
		public static Path getPathInSchema()
		{
			return _Root_Area;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _Meid = Path.parse("./meid");
		public static final Path _Parents = Path.parse("./parents");
		public static final Path _Locations = Path.parse("./locations");
		public static final Path _HierarchyPaths = Path.parse("./hierarchyPaths");
		public static final Path _BusinessParties = Path.parse("./businessParties");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_CMSArea
	{
		private static final Path _Root_CMSArea = _Root.add("CMSArea");
		public static Path getPathInSchema()
		{
			return _Root_CMSArea;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _Parents = Path.parse("./parents");
		public static final Path _Locations = Path.parse("./locations");
		public static final Path _HierarchyPaths = Path.parse("./hierarchyPaths");
		public static final Path _BusinessParties = Path.parse("./businessParties");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_FleetArea
	{
		private static final Path _Root_FleetArea = _Root.add("FleetArea");
		public static Path getPathInSchema()
		{
			return _Root_FleetArea;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _Parents = Path.parse("./parents");
		public static final Path _Locations = Path.parse("./locations");
		public static final Path _HierarchyPaths = Path.parse("./hierarchyPaths");
		public static final Path _BusinessParties = Path.parse("./businessParties");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_ReservationArea
	{
		private static final Path _Root_ReservationArea = _Root.add("ReservationArea");
		public static Path getPathInSchema()
		{
			return _Root_ReservationArea;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _Parents = Path.parse("./parents");
		public static final Path _Locations = Path.parse("./locations");
		public static final Path _HierarchyPaths = Path.parse("./hierarchyPaths");
		public static final Path _BusinessParties = Path.parse("./businessParties");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	public static final Path _Root_AreaData = _Root.add("AreaData");

	// Table type path
	public final class _Root_AreaData_AreaBusinessPartyRelationship
	{
		private static final Path _Root_AreaData_AreaBusinessPartyRelationship = _Root_AreaData.add("AreaBusinessPartyRelationship");
		public static Path getPathInSchema()
		{
			return _Root_AreaData_AreaBusinessPartyRelationship;
		}
		public static final Path _Area = Path.parse("./area");
		public static final Path _BusinessParty = Path.parse("./businessParty");
		public static final Path _ContactType = Path.parse("./contactType");
		public static final Path _ReportingLevel = Path.parse("./reportingLevel");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_AreaData_CMSAreaBusinessPartyRelationship
	{
		private static final Path _Root_AreaData_CMSAreaBusinessPartyRelationship = _Root_AreaData.add("CMSAreaBusinessPartyRelationship");
		public static Path getPathInSchema()
		{
			return _Root_AreaData_CMSAreaBusinessPartyRelationship;
		}
		public static final Path _CmsArea = Path.parse("./cmsArea");
		public static final Path _BusinessParty = Path.parse("./businessParty");
		public static final Path _ContactType = Path.parse("./contactType");
		public static final Path _ReportingLevel = Path.parse("./reportingLevel");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_AreaData_ReservationAreaBusinessPartyRelationship
	{
		private static final Path _Root_AreaData_ReservationAreaBusinessPartyRelationship = _Root_AreaData.add("ReservationAreaBusinessPartyRelationship");
		public static Path getPathInSchema()
		{
			return _Root_AreaData_ReservationAreaBusinessPartyRelationship;
		}
		public static final Path _ReservationArea = Path.parse("./reservationArea");
		public static final Path _BusinessParty = Path.parse("./businessParty");
		public static final Path _ContactType = Path.parse("./contactType");
		public static final Path _ReportingLevel = Path.parse("./reportingLevel");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_AreaData_FleetAreaBusinessPartyRelationship
	{
		private static final Path _Root_AreaData_FleetAreaBusinessPartyRelationship = _Root_AreaData.add("FleetAreaBusinessPartyRelationship");
		public static Path getPathInSchema()
		{
			return _Root_AreaData_FleetAreaBusinessPartyRelationship;
		}
		public static final Path _FleetArea = Path.parse("./fleetArea");
		public static final Path _BusinessParty = Path.parse("./businessParty");
		public static final Path _ContactType = Path.parse("./contactType");
		public static final Path _ReportingLevel = Path.parse("./reportingLevel");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_AreaData_AreaTypeLocationHierarchyRelationship
	{
		private static final Path _Root_AreaData_AreaTypeLocationHierarchyRelationship = _Root_AreaData.add("AreaTypeLocationHierarchyRelationship");
		public static Path getPathInSchema()
		{
			return _Root_AreaData_AreaTypeLocationHierarchyRelationship;
		}
		public static final Path _AreaType = Path.parse("./areaType");
		public static final Path _LocationHierarchy = Path.parse("./locationHierarchy");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationHierarchy
	{
		private static final Path _Root_LocationHierarchy = _Root.add("LocationHierarchy");
		public static Path getPathInSchema()
		{
			return _Root_LocationHierarchy;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Node = Path.parse("./node");
		public static final Path _Name = Path.parse("./name");
		public static final Path _Description = Path.parse("./description");
		public static final Path _BusinessParties = Path.parse("./businessParties");
		public static final Path _IsARegion = Path.parse("./isARegion");
		public static final Path _HierarchyNodeType = Path.parse("./hierarchyNodeType");
		public static final Path _HierarchyDefinitionNode = Path.parse("./hierarchyDefinitionNode");
		public static final Path _Parents = Path.parse("./parents");
		public static final Path _HierarchyPaths = Path.parse("./hierarchyPaths");
		public static final Path _Children = Path.parse("./children");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	public static final Path _Root_HierarchyDefinitionData = _Root.add("HierarchyDefinitionData");

	// Table type path
	public final class _Root_HierarchyDefinitionData_HierarchyStructureDefinition
	{
		private static final Path _Root_HierarchyDefinitionData_HierarchyStructureDefinition = _Root_HierarchyDefinitionData.add("HierarchyStructureDefinition");
		public static Path getPathInSchema()
		{
			return _Root_HierarchyDefinitionData_HierarchyStructureDefinition;
		}
		public static final Path _Id = Path.parse("./id");
		public static final Path _Name = Path.parse("./name");
		public static final Path _HierarchyNodeType = Path.parse("./HierarchyNodeType");
		public static final Path _HierarchyMembership = Path.parse("./hierarchyMembership");
		public static final Path _Countries = Path.parse("./countries");
		public static final Path _Parents = Path.parse("./parents");
		public static final Path _Children = Path.parse("./children");
		public static final Path _ContactTypes = Path.parse("./contactTypes");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_HierarchyDefinitionData_LocationHierarchyBusinessPartyRelationship
	{
		private static final Path _Root_HierarchyDefinitionData_LocationHierarchyBusinessPartyRelationship = _Root_HierarchyDefinitionData.add("LocationHierarchyBusinessPartyRelationship");
		public static Path getPathInSchema()
		{
			return _Root_HierarchyDefinitionData_LocationHierarchyBusinessPartyRelationship;
		}
		public static final Path _LocationHierarchy = Path.parse("./locationHierarchy");
		public static final Path _ContactType = Path.parse("./contactType");
		public static final Path _BusinessParty = Path.parse("./businessParty");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_HierarchyDefinitionData_LocationStructureDefinitionContactTypeRelationship
	{
		private static final Path _Root_HierarchyDefinitionData_LocationStructureDefinitionContactTypeRelationship = _Root_HierarchyDefinitionData.add("LocationStructureDefinitionContactTypeRelationship");
		public static Path getPathInSchema()
		{
			return _Root_HierarchyDefinitionData_LocationStructureDefinitionContactTypeRelationship;
		}
		public static final Path _LocationStructureDefinition = Path.parse("./locationStructureDefinition");
		public static final Path _ContactType = Path.parse("./contactType");
		public static final Path _IsRequired = Path.parse("./isRequired");
		public static final Path _IsOnlyContactAllowed = Path.parse("./isOnlyContactAllowed");
		public static final Path _ReportingLevel = Path.parse("./reportingLevel");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_HierarchyDefinitionData_LocationStructureDefinitionParentRelationship
	{
		private static final Path _Root_HierarchyDefinitionData_LocationStructureDefinitionParentRelationship = _Root_HierarchyDefinitionData.add("LocationStructureDefinitionParentRelationship");
		public static Path getPathInSchema()
		{
			return _Root_HierarchyDefinitionData_LocationStructureDefinitionParentRelationship;
		}
		public static final Path _LocationStructureDefinition = Path.parse("./locationStructureDefinition");
		public static final Path _Parent = Path.parse("./parent");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_HierarchyDefinitionData_LocationStructureDefinitionCountryRelationship
	{
		private static final Path _Root_HierarchyDefinitionData_LocationStructureDefinitionCountryRelationship = _Root_HierarchyDefinitionData.add("LocationStructureDefinitionCountryRelationship");
		public static Path getPathInSchema()
		{
			return _Root_HierarchyDefinitionData_LocationStructureDefinitionCountryRelationship;
		}
		public static final Path _LocationStructureDefinition = Path.parse("./locationStructureDefinition");
		public static final Path _Country = Path.parse("./country");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	// ===============================================

}
