package com.hertz.mdm.location.path;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX5 5.8.1 [1067], at  2018/01/12 17:19:20 [EST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: hertz-mdm, path: /WEB-INF/ebx/schemas/LocationReferenceDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface LocationReferencePaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Prefix:  ''.
	// Statistics:
	//		395 path constants.
	//		145 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Ancillary
	{
		private static final Path _Root_Ancillary = _Root.add("Ancillary");
		public static Path getPathInSchema()
		{
			return _Root_Ancillary;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _Type = Path.parse("./type");
		public static final Path _IsAncillariesGroup = Path.parse("./isAncillariesGroup");
		public static final Path _IsRequiredByCorporate = Path.parse("./isRequiredByCorporate");
		public static final Path _Ancillaries = Path.parse("./ancillaries");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_AncillaryGroupAncillaryRelationship
	{
		private static final Path _Root_AncillaryGroupAncillaryRelationship = _Root.add("AncillaryGroupAncillaryRelationship");
		public static Path getPathInSchema()
		{
			return _Root_AncillaryGroupAncillaryRelationship;
		}
		public static final Path _AncillaryGroup = Path.parse("./ancillaryGroup");
		public static final Path _Ancillary = Path.parse("./ancillary");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_AreaType
	{
		private static final Path _Root_AreaType = _Root.add("AreaType");
		public static Path getPathInSchema()
		{
			return _Root_AreaType;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_ContactType
	{
		private static final Path _Root_ContactType = _Root.add("ContactType");
		public static Path getPathInSchema()
		{
			return _Root_ContactType;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _BusinessPartyType = Path.parse("./businessPartyType");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_CountryMinimumMaximumAge
	{
		private static final Path _Root_CountryMinimumMaximumAge = _Root.add("CountryMinimumMaximumAge");
		public static Path getPathInSchema()
		{
			return _Root_CountryMinimumMaximumAge;
		}
		public static final Path _Country = Path.parse("./country");
		public static final Path _MinimunAge = Path.parse("./minimunAge");
		public static final Path _MaximumAge = Path.parse("./maximumAge");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_HierarchyNodeType
	{
		private static final Path _Root_HierarchyNodeType = _Root.add("HierarchyNodeType");
		public static Path getPathInSchema()
		{
			return _Root_HierarchyNodeType;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_Indicator
	{
		private static final Path _Root_Indicator = _Root.add("Indicator");
		public static Path getPathInSchema()
		{
			return _Root_Indicator;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _IndicatorCategory = Path.parse("./indicatorCategory");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_IndicatorCategory
	{
		private static final Path _Root_IndicatorCategory = _Root.add("IndicatorCategory");
		public static Path getPathInSchema()
		{
			return _Root_IndicatorCategory;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationCity
	{
		private static final Path _Root_LocationCity = _Root.add("LocationCity");
		public static Path getPathInSchema()
		{
			return _Root_LocationCity;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _Country = Path.parse("./country");
		public static final Path _StateProvince = Path.parse("./stateProvince");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationRelationshipType
	{
		private static final Path _Root_LocationRelationshipType = _Root.add("LocationRelationshipType");
		public static Path getPathInSchema()
		{
			return _Root_LocationRelationshipType;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_ManagementEntityId
	{
		private static final Path _Root_ManagementEntityId = _Root.add("ManagementEntityId");
		public static Path getPathInSchema()
		{
			return _Root_ManagementEntityId;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_OEMDropShipCode
	{
		private static final Path _Root_OEMDropShipCode = _Root.add("OEMDropShipCode");
		public static Path getPathInSchema()
		{
			return _Root_OEMDropShipCode;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_OfficeEquipmentType
	{
		private static final Path _Root_OfficeEquipmentType = _Root.add("OfficeEquipmentType");
		public static Path getPathInSchema()
		{
			return _Root_OfficeEquipmentType;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_OperationsOwnershipType
	{
		private static final Path _Root_OperationsOwnershipType = _Root.add("OperationsOwnershipType");
		public static Path getPathInSchema()
		{
			return _Root_OperationsOwnershipType;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _IsStaffedByHertzPersonnel = Path.parse("./isStaffedByHertzPersonnel");
		public static final Path _IntelligentLocationIdOwnershipCode = Path.parse("./intelligentLocationIdOwnershipCode");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_RefuelingFee
	{
		private static final Path _Root_RefuelingFee = _Root.add("RefuelingFee");
		public static Path getPathInSchema()
		{
			return _Root_RefuelingFee;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _RefuelingFeeAmount = Path.parse("./refuelingFeeAmount");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_ServiceHoursType
	{
		private static final Path _Root_ServiceHoursType = _Root.add("ServiceHoursType");
		public static Path getPathInSchema()
		{
			return _Root_ServiceHoursType;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	public static final Path _Root_LocationTypes = _Root.add("LocationTypes");

	// Table type path
	public final class _Root_LocationTypes_LocationTypeGroup
	{
		private static final Path _Root_LocationTypes_LocationTypeGroup = _Root_LocationTypes.add("LocationTypeGroup");
		public static Path getPathInSchema()
		{
			return _Root_LocationTypes_LocationTypeGroup;
		}
		public static final Path _LocationTypeGroupType = Path.parse("./locationTypeGroupType");
		public static final Path _LocationTypeGroupParent = Path.parse("./locationTypeGroupParent");
		public static final Path _SubFunctionType = Path.parse("./subFunctionType");
		public static final Path __areMultipleSelectionsAllowed = Path.parse("./_areMultipleSelectionsAllowed");
		public static final Path _LocationTypeGroupPath = Path.parse("./locationTypeGroupPath");
		public static final Path _LocationTypes = Path.parse("./locationTypes");
		public static final Path _NoMultipleLocationTypeGroup = Path.parse("./noMultipleLocationTypeGroup");
		public static final Path _IsAirportOperations = Path.parse("./isAirportOperations");
		public static final Path _RentalType = Path.parse("./rentalType");
		public static final Path _IsLeafNode = Path.parse("./isLeafNode");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationTypes_LocationTypeGroupType
	{
		private static final Path _Root_LocationTypes_LocationTypeGroupType = _Root_LocationTypes.add("LocationTypeGroupType");
		public static Path getPathInSchema()
		{
			return _Root_LocationTypes_LocationTypeGroupType;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _AreMultipleSelectionsAllowed = Path.parse("./areMultipleSelectionsAllowed");
		public static final Path _Accriss = Path.parse("./accriss");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationTypes_LocationType
	{
		private static final Path _Root_LocationTypes_LocationType = _Root_LocationTypes.add("LocationType");
		public static Path getPathInSchema()
		{
			return _Root_LocationTypes_LocationType;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_LocationTypes_LocationTypeGroupLocationTypeRelationship
	{
		private static final Path _Root_LocationTypes_LocationTypeGroupLocationTypeRelationship = _Root_LocationTypes.add("LocationTypeGroupLocationTypeRelationship");
		public static Path getPathInSchema()
		{
			return _Root_LocationTypes_LocationTypeGroupLocationTypeRelationship;
		}
		public static final Path _LocationTypeGroup = Path.parse("./locationTypeGroup");
		public static final Path _LocationType = Path.parse("./locationType");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_MDMLocationReferenceCrossReference
	{
		private static final Path _Root_MDMLocationReferenceCrossReference = _Root.add("MDMLocationReferenceCrossReference");
		public static Path getPathInSchema()
		{
			return _Root_MDMLocationReferenceCrossReference;
		}
		public static final Path _Base = Path.parse("./base");
		public static final Path _Base_Id = Path.parse("./base/id");
		public static final Path _Base_Name = Path.parse("./base/name");
		public static final Path _Base_Description = Path.parse("./base/description");
		public static final Path _EbxReplicationTableName = Path.parse("./ebxReplicationTableName");
		public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
		public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
		public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
		public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	// ===============================================

}
