package com.hertz.mdm.RDM.path;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX5 5.8.1 [1067], at  2018/02/14 19:07:40 [EST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Publication: CrossReferenceDataModel].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface CrossReferencePaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Statistics:
	//		331 path constants.
	//		188 leaf nodes.
	public static final Path _Root = Path.parse("/root");
	public static final Path _Root_Cross_Reference_Data = _Root.add("Cross_Reference_Data");

	// Table type path
	public final class _Root_Cross_Reference_Data_RDM_LOV_TYPE
	{
		private static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE = _Root_Cross_Reference_Data.add("RDM_LOV_TYPE");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_RDM_LOV_TYPE;
		}
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_LOV_COMMENTS = Path.parse("./LOV_COMMENTS");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_TYPE_LOV_END_DT = Path.parse("./LOV_END_DT");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_RDM_LOV_STATUS
	{
		private static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS = _Root_Cross_Reference_Data.add("RDM_LOV_STATUS");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_RDM_LOV_STATUS;
		}
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_LOV_CODE = Path.parse("./LOV_CODE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_LOV_VALUE = Path.parse("./LOV_VALUE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_LOV_COMMENTS = Path.parse("./LOV_COMMENTS");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_STATUS_LOV_END_DT = Path.parse("./LOV_END_DT");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG
	{
		private static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG = _Root_Cross_Reference_Data.add("RDM_LOV_SYSTEM_REG");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG;
		}
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_LOV_EXT_SYST_ID = Path.parse("./LOV_EXT_SYST_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_LOV_EXT_SYST_NAME = Path.parse("./LOV_EXT_SYST_NAME");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_STATUS = Path.parse("./STATUS");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_LOV_COMMENTS = Path.parse("./LOV_COMMENTS");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_SYSTEM_REG_LOV_END_DT = Path.parse("./LOV_END_DT");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS
	{
		private static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS = _Root_Cross_Reference_Data.add("RDM_LOV_ANCILLARY_PRODUCTS");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS;
		}
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_LOV_CODE = Path.parse("./LOV_CODE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_LOV_VALUE = Path.parse("./LOV_VALUE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_LOV_END_DT = Path.parse("./LOV_END_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ANCILLARY_PRODUCTS_TRANSLATION_ID = Path.parse("./TRANSLATION_ID");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS
	{
		private static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS = _Root_Cross_Reference_Data.add("SOURCE_LOV_ANCILLARY_PRODUCTS");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS;
		}
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LOV_CODE = Path.parse("./LOV_CODE");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LOV_VALUE = Path.parse("./LOV_VALUE");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LOV_EXT_SYST_ID = Path.parse("./LOV_EXT_SYST_ID");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_LOV_END_DT = Path.parse("./LOV_END_DT");
		public static final Path _Root_Cross_Reference_Data_SOURCE_LOV_ANCILLARY_PRODUCTS_TRANSLATION_ID = Path.parse("./TRANSLATION_ID");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS
	{
		private static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS = _Root_Cross_Reference_Data.add("TARGET_LOV_ANCILLARY_PRODUCTS");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS;
		}
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LOV_CODE = Path.parse("./LOV_CODE");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LOV_VALUE = Path.parse("./LOV_VALUE");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LOV_EXT_SYST_ID = Path.parse("./LOV_EXT_SYST_ID");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_LOV_END_DT = Path.parse("./LOV_END_DT");
		public static final Path _Root_Cross_Reference_Data_TARGET_LOV_ANCILLARY_PRODUCTS_TRANSLATION_ID = Path.parse("./TRANSLATION_ID");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_RDM_ANCILLARY_TRANSLATION
	{
		private static final Path _Root_Cross_Reference_Data_RDM_ANCILLARY_TRANSLATION = _Root_Cross_Reference_Data.add("RDM_ANCILLARY_TRANSLATION");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_RDM_ANCILLARY_TRANSLATION;
		}
		public static final Path _Root_Cross_Reference_Data_RDM_ANCILLARY_TRANSLATION_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_ANCILLARY_TRANSLATION_Source_Details = Path.parse("./Source_Details");
		public static final Path _Root_Cross_Reference_Data_RDM_ANCILLARY_TRANSLATION_RDM_Association = Path.parse("./RDM_Association");
		public static final Path _Root_Cross_Reference_Data_RDM_ANCILLARY_TRANSLATION_TARGET_ASSOCIATION = Path.parse("./TARGET_ASSOCIATION");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY
	{
		private static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY = _Root_Cross_Reference_Data.add("RDM_LOV_ISO_COUNTRY");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY;
		}
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_ISO_ALPHA_2_CODE = Path.parse("./LOV_ISO_ALPHA_2_CODE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_ISO_ALPHA_3_CODE = Path.parse("./LOV_ISO_ALPHA_3_CODE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_ISO_NUMERIC_CODE = Path.parse("./LOV_ISO_NUMERIC_CODE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_SHORT_NAME_EN = Path.parse("./LOV_SHORT_NAME_EN");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_FULL_NAME_EN = Path.parse("./LOV_FULL_NAME_EN");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_SHORT_NAME_UPPER_CASE_EN = Path.parse("./LOV_SHORT_NAME_UPPER_CASE_EN");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_INDEPENDENT = Path.parse("./LOV_INDEPENDENT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_EXT_SYST_ID = Path.parse("./LOV_EXT_SYST_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_END_DT = Path.parse("./LOV_END_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_COUNTRY_LOV_ORDER_BY = Path.parse("./LOV_ORDER_BY");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION
	{
		private static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION = _Root_Cross_Reference_Data.add("RDM_LOV_ISO_SUB_DIVISION");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION;
		}
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_SUB_DIVISION_CODE = Path.parse("./LOV_SUB_DIVISION_CODE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_SUB_DIVISION_COUNTRY = Path.parse("./LOV_SUB_DIVISION_COUNTRY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_SUB_DIVISION_NAME = Path.parse("./LOV_SUB_DIVISION_NAME");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_SUB_DIVISION__LOCAL_VARIATION = Path.parse("./LOV_SUB_DIVISION__LOCAL_VARIATION");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_EXT_SYST_ID = Path.parse("./LOV_EXT_SYST_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_END_DT = Path.parse("./LOV_END_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_SUB_DIVISION_LOV_ORDER_BY = Path.parse("./LOV_ORDER_BY");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY
	{
		private static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY = _Root_Cross_Reference_Data.add("RDM_LOV_ISO_CURRENCY");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY;
		}
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_CURRENCY_CODE = Path.parse("./LOV_CURRENCY_CODE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_CURRENCY_COUNTRY = Path.parse("./LOV_CURRENCY_COUNTRY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_CURRENCY_VALUE = Path.parse("./LOV_CURRENCY_VALUE");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_CURRENCY_UNIT = Path.parse("./LOV_CURRENCY_UNIT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_EXT_SYST_ID = Path.parse("./LOV_EXT_SYST_ID");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_END_DT = Path.parse("./LOV_END_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_RDM_LOV_ISO_CURRENCY_LOV_ORDER_BY = Path.parse("./LOV_ORDER_BY");
	} 
	public static final Path _Root_Cross_Reference_Data_PaymentCardType = _Root_Cross_Reference_Data.add("PaymentCardType");

	// Table type path
	public final class _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE
	{
		private static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE = _Root_Cross_Reference_Data_PaymentCardType.add("RDM_LOV_PAYMENT_CARD_TYPE");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE;
		}
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_LOV_CODE = Path.parse("./LOV_CODE");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_LOV_VALUE = Path.parse("./LOV_VALUE");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_LOV_END_DT = Path.parse("./LOV_END_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_LOV_PAYMENT_CARD_TYPE_TRANSLATION_ID = Path.parse("./TRANSLATION_ID");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE
	{
		private static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE = _Root_Cross_Reference_Data_PaymentCardType.add("SOURCE_LOV_PAYMENT_CARD_TYPE");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE;
		}
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LOV_CODE = Path.parse("./LOV_CODE");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LOV_VALUE = Path.parse("./LOV_VALUE");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LOV_EXT_SYST_ID = Path.parse("./LOV_EXT_SYST_ID");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_LOV_END_DT = Path.parse("./LOV_END_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_SOURCE_LOV_PAYMENT_CARD_TYPE_TRANSLATION_ID = Path.parse("./TRANSLATION_ID");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE
	{
		private static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE = _Root_Cross_Reference_Data_PaymentCardType.add("TARGET_LOV_PAYMENT_CARD_TYPE");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE;
		}
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LOV_TYPE = Path.parse("./LOV_TYPE");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LOV_CODE = Path.parse("./LOV_CODE");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LOV_VALUE = Path.parse("./LOV_VALUE");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LOV_EXT_SYST_ID = Path.parse("./LOV_EXT_SYST_ID");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LOV_DESCRIPTION = Path.parse("./LOV_DESCRIPTION");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LOV_STATUS = Path.parse("./LOV_STATUS");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_CREATED_BY = Path.parse("./CREATED_BY");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_CREATED_DT = Path.parse("./CREATED_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LAST_UPD_BY = Path.parse("./LAST_UPD_BY");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LAST_UPD_DT = Path.parse("./LAST_UPD_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_DB_LAST_UPD_SRC = Path.parse("./DB_LAST_UPD_SRC");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LOV_EFFECTIVE_DT = Path.parse("./LOV_EFFECTIVE_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_LOV_END_DT = Path.parse("./LOV_END_DT");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_TARGET_LOV_PAYMENT_CARD_TYPE_TRANSLATION_ID = Path.parse("./TRANSLATION_ID");
	} 

	// Table type path
	public final class _Root_Cross_Reference_Data_PaymentCardType_RDM_PAYMENT_CARD_TYPE_TRANSLATION
	{
		private static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_PAYMENT_CARD_TYPE_TRANSLATION = _Root_Cross_Reference_Data_PaymentCardType.add("RDM_PAYMENT_CARD_TYPE_TRANSLATION");
		public static Path getPathInSchema()
		{
			return _Root_Cross_Reference_Data_PaymentCardType_RDM_PAYMENT_CARD_TYPE_TRANSLATION;
		}
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_PAYMENT_CARD_TYPE_TRANSLATION_ROW_ID = Path.parse("./ROW_ID");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_PAYMENT_CARD_TYPE_TRANSLATION_Source_Details = Path.parse("./Source_Details");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_PAYMENT_CARD_TYPE_TRANSLATION_RDM_Association = Path.parse("./RDM_Association");
		public static final Path _Root_Cross_Reference_Data_PaymentCardType_RDM_PAYMENT_CARD_TYPE_TRANSLATION_TARGET_ASSOCIATION = Path.parse("./TARGET_ASSOCIATION");
	} 
	// ===============================================

}
