package com.hertz.mdm.businessparty.path;

import com.orchestranetworks.schema.Path;
/**
 * Generated by EBX5 5.7.1 fix B [1034:0005], at  2017/06/13 17:44:25 [EDT].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: hertz-mdm, path: /WEB-INF/ebx/schemas/BusinessPartyReferenceDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface BusinessPartyReferencePaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Prefix:  ''.
	// Statistics:
	//		55 path constants.
	//		21 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_BusinessPartyRoleType {
		private static final Path _Root_BusinessPartyRoleType = _Root.add("BusinessPartyRoleType");
		public static Path getPathInSchema()
		{
			return _Root_BusinessPartyRoleType;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _RoleCategory = Path.parse("./roleCategory");
	public static final Path _BusinessPartyType = Path.parse("./businessPartyType");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_BusinessPartyType {
		private static final Path _Root_BusinessPartyType = _Root.add("BusinessPartyType");
		public static Path getPathInSchema()
		{
			return _Root_BusinessPartyType;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_MDMBusinessPartyReferenceCrossReference {
		private static final Path _Root_MDMBusinessPartyReferenceCrossReference = _Root.add("MDMBusinessPartyReferenceCrossReference");
		public static Path getPathInSchema()
		{
			return _Root_MDMBusinessPartyReferenceCrossReference;
		}
	public static final Path _Base = Path.parse("./base");
	public static final Path _Base_Id = Path.parse("./base/id");
	public static final Path _Base_Name = Path.parse("./base/name");
	public static final Path _Base_Description = Path.parse("./base/description");
	public static final Path _MdmReplicationTableName = Path.parse("./mdmReplicationTableName");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	// ===============================================

}
