package com.hertz.mdm.businessparty.path;

import com.orchestranetworks.schema.Path;
/**
 * Generated by EBX5 5.7.1 fix B [1034:0005], at  2017/09/04 10:57:48 [EDT].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: hertz-mdm, path: /WEB-INF/ebx/schemas/BusinessPartyDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface BusinessPartyPaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Prefix:  ''.
	// Statistics:
	//		118 path constants.
	//		64 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_BusinessParty {
		private static final Path _Root_BusinessParty = _Root.add("BusinessParty");
		public static Path getPathInSchema()
		{
			return _Root_BusinessParty;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _Name = Path.parse("./name");
	public static final Path _BusinessPartyType = Path.parse("./businessPartyType");
	public static final Path _OrganizationParent = Path.parse("./organizationParent");
	public static final Path _EbxUser = Path.parse("./ebxUser");
	public static final Path _EbxUserLogin = Path.parse("./ebxUserLogin");
	public static final Path _Addresses = Path.parse("./Addresses");
	public static final Path _EMailAddresses = Path.parse("./eMailAddresses");
	public static final Path _Phones = Path.parse("./phones");
	public static final Path _OrganziationMembers = Path.parse("./organziationMembers");
	public static final Path _Roles = Path.parse("./roles");
	public static final Path _EbxRoles = Path.parse("./ebxRoles");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	public static final Path _Root_BusinessPartyData = _Root.add("BusinessPartyData");

	// Table type path
	public final class _Root_BusinessPartyData_BusinessPartyRole {
		private static final Path _Root_BusinessPartyData_BusinessPartyRole = _Root_BusinessPartyData.add("BusinessPartyRole");
		public static Path getPathInSchema()
		{
			return _Root_BusinessPartyData_BusinessPartyRole;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _BusinessParty = Path.parse("./businessParty");
	public static final Path _BusinessPartyRoleType = Path.parse("./businessPartyRoleType");
	public static final Path _RoleCategory = Path.parse("./roleCategory");
	public static final Path _BusinessPartyType = Path.parse("./businessPartyType");
	public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_BusinessPartyData_Address {
		private static final Path _Root_BusinessPartyData_Address = _Root_BusinessPartyData.add("Address");
		public static Path getPathInSchema()
		{
			return _Root_BusinessPartyData_Address;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _BusinessParty = Path.parse("./businessParty");
	public static final Path _PrimarySecondary = Path.parse("./primarySecondary");
	public static final Path _Type = Path.parse("./type");
	public static final Path _Address = Path.parse("./Address");
	public static final Path _Address_StreetNumber = Path.parse("./Address/streetNumber");
	public static final Path _Address_AddressLine1 = Path.parse("./Address/addressLine1");
	public static final Path _Address_AddressLine2 = Path.parse("./Address/addressLine2");
	public static final Path _Address_AddressLine3 = Path.parse("./Address/addressLine3");
	public static final Path _Address_Country = Path.parse("./Address/country");
	public static final Path _Address_StateProvince = Path.parse("./Address/stateProvince");
	public static final Path _Address_County = Path.parse("./Address/county");
	public static final Path _Address_City = Path.parse("./Address/city");
	public static final Path _Address_PostalCode = Path.parse("./Address/postalCode");
	public static final Path _Address_Attention = Path.parse("./Address/attention");
	public static final Path _Address_Status = Path.parse("./Address/status");
	public static final Path _GeographicPoint = Path.parse("./GeographicPoint");
	public static final Path _GeographicPoint_Latitude = Path.parse("./GeographicPoint/latitude");
	public static final Path _GeographicPoint_Longitude = Path.parse("./GeographicPoint/longitude");
	public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_BusinessPartyData_Email {
		private static final Path _Root_BusinessPartyData_Email = _Root_BusinessPartyData.add("Email");
		public static Path getPathInSchema()
		{
			return _Root_BusinessPartyData_Email;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _BusinessParty = Path.parse("./businessParty");
	public static final Path _PrimarySecondary = Path.parse("./primarySecondary");
	public static final Path _EMailType = Path.parse("./eMailType");
	public static final Path _EMailAddress = Path.parse("./eMailAddress");
	public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 

	// Table type path
	public final class _Root_BusinessPartyData_Phone {
		private static final Path _Root_BusinessPartyData_Phone = _Root_BusinessPartyData.add("Phone");
		public static Path getPathInSchema()
		{
			return _Root_BusinessPartyData_Phone;
		}
	public static final Path _Id = Path.parse("./id");
	public static final Path _BusinessParty = Path.parse("./businessParty");
	public static final Path _PrimarySecondary = Path.parse("./primarySecondary");
	public static final Path _PhoneType = Path.parse("./phoneType");
	public static final Path _PhoneNumber = Path.parse("./phoneNumber");
	public static final Path _Extension = Path.parse("./extension");
	public static final Path _AdditionalInformation = Path.parse("./additionalInformation");
	public static final Path _EffectiveStartEndDates = Path.parse("./effectiveStartEndDates");
	public static final Path _EffectiveStartEndDates_StartDate = Path.parse("./effectiveStartEndDates/startDate");
	public static final Path _EffectiveStartEndDates_EndDate = Path.parse("./effectiveStartEndDates/endDate");
	public static final Path _IsRecordActive = Path.parse("./isRecordActive");
	} 
	// ===============================================

}
